/**
 * Tracked Fields Registry
 *
 * Defines which fields to track for each Data Lake table, plus
 * metadata about how each table's primary key maps to generic
 * search filters (recordno/recordsuf).
 *
 * To add a new module:
 *   1. Add TABLE_CONFIG entries for each table
 *   2. Add TRACKED_FIELDS entries for each table
 *   3. Add field definitions to server/tracked-fields.js (this file)
 *   4. Create a new page in src/pages/
 */

// ─── Table Configuration ───
// Maps each table's primary key columns so the generic search
// (which sends pono/posuf from the frontend) gets translated
// to the correct column names in the SQL query.

const TABLE_CONFIG = {
  // Purchases
  poeh:  { recordKey: 'pono', suffixKey: 'posuf', lineKey: null, recordKeyType: 'number' },
  poel:  { recordKey: 'pono', suffixKey: 'posuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Orders
  oeeh:  { recordKey: 'orderno', suffixKey: 'ordersuf', lineKey: null, recordKeyType: 'number' },
  oeel:  { recordKey: 'orderno', suffixKey: 'ordersuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Product / Warehouse
  icsp:  { recordKey: 'prod', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  icsw:  { recordKey: 'prod', suffixKey: null, lineKey: 'whse', recordKeyType: 'string' },

  // Customers
  arsc:  { recordKey: 'custno', suffixKey: null, lineKey: null, recordKeyType: 'number' },
  arss:  { recordKey: 'custno', suffixKey: null, lineKey: 'shipto', recordKeyType: 'number' },

  // Catalog
  icsc:  { recordKey: 'catalog', suffixKey: null, lineKey: null, recordKeyType: 'string' },

  // Transfers
  wteh:  { recordKey: 'wtno', suffixKey: 'wtsuf', lineKey: null, recordKeyType: 'number' },
  wtel:  { recordKey: 'wtno', suffixKey: 'wtsuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Customer Pricing
  pdsc:  { recordKey: 'pdrecno', suffixKey: null, lineKey: null, recordKeyType: 'number' },

  // Vendor Pricing
  pdsv:  { recordKey: 'vendno', suffixKey: null, lineKey: 'prod', recordKeyType: 'number' },

  // Vendors
  apsv:  { recordKey: 'vendno', suffixKey: null, lineKey: null, recordKeyType: 'number' },
  apss:  { recordKey: 'vendno', suffixKey: null, lineKey: 'shipfmno', recordKeyType: 'number' },

  // Inventory
  icet:  { recordKey: 'prod', suffixKey: null, lineKey: 'whse', recordKeyType: 'string' },
  icsep: { recordKey: 'prod', suffixKey: null, lineKey: 'whse', recordKeyType: 'string' },
  icset: { recordKey: 'prod', suffixKey: null, lineKey: 'whse', recordKeyType: 'string' },

  // Security
  sasoo:       { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  pv_user:     { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  pv_secure:   { recordKey: 'oper2', suffixKey: null, lineKey: 'FunctionName', recordKeyType: 'string' },
  authsecure:  { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string', groupFields: ['oper2', 'ourproc', 'key1'] },
};

// ─── Tracked Fields ───
// Each entry: { label: 'Display Name', desc: 'Description for expanded row' }

const TRACKED_FIELDS = {

  // ─── Purchases ───

  poeh: {
    stagecd:    { label: 'Stage Code', desc: 'the stage of the PO. Content: 0 - Entered, 1 - Ordered, 2 - Printed, 3 - Acknowledged, 4 - Pre-receiving, 5 - Received, 6 - Costed, 7 - Closed, 9 - Cancelled' },
    approvty:   { label: 'Approval', desc: '(Y)es, (N)o or Any Other Character for Hold' },
    duedt:      { label: 'Due Date', desc: 'Due date' },
    expshipdt:  { label: 'Expected Ship Date', desc: 'Expected ship date' },
    reqshipdt:  { label: 'Requested Ship Date', desc: 'Requested Ship Date is the date that you have requested the product from the vendor' },
    frttermscd: { label: 'Freight Terms', desc: 'Freight Terms. Content: Validated against valid SASTA value - carrier freight terms' },
    termstype:  { label: 'Terms Type', desc: 'Default terms comes from apsv.termstype. Value is set up in the Terms table' },
    shipviaty:  { label: 'Ship Via', desc: 'Ship via type' },
    buyer:      { label: 'Buyer', desc: 'Buyer' },
    whse:       { label: 'Warehouse', desc: 'Warehouse id. This is the same value as in the POEH table' },
    vendno:     { label: 'Vendor Number', desc: 'Vendor number' },
    refer:      { label: 'Reference', desc: 'Reference' },
    vendordno:  { label: 'Vendor Order Number', desc: 'Vendor order number' },
    receiptdt:  { label: 'Receipt Date', desc: 'Date the PO was received' },
    rcvoperinit: { label: 'Received By', desc: 'Operator who received the PO' },
    costeddt:   { label: 'Costed Date', desc: 'The date this PO was last costed' },
    paiddt:     { label: 'Paid Date', desc: 'Date the PO was paid' },
    printeddt:  { label: 'Printed Date', desc: 'Date the PO was printed' },
    printfl:    { label: 'Printed', desc: 'Set to yes when a change occurs on the PO that requires a reprint' },
    totinvamt:  { label: 'Total Invoice Amount', desc: 'Total invoiced amount' },
    totuinvamt: { label: 'Total Uninvoiced Amount', desc: 'Total Uninvoiced GL Amount' },
    totqtycost: { label: 'Total Qty Cost', desc: 'Total quantity cost' },
    jrnlno:     { label: 'Journal Number', desc: 'Receiving journal #' },
    ackdt:      { label: 'Acknowledgment Date', desc: 'Purchase order acknowledgement date.' },
    ackoper:    { label: 'Acknowledged By', desc: 'Operator that last modifed the "acktype" field.' },
    acktype:    { label: 'Acknowledgment Type', desc: 'Description: Processing type for update of the "ackrsn" field. Content: Manual, Reset, EDI, blank' },
    countrycd:  { label: 'Country', desc: 'Country code' },
    dueoverfl:  { label: 'Due Date Override', desc: 'Due date override flag' },
    glupdfl:    { label: 'GL Updated', desc: 'GL updated flag' },
    laststagecd: { label: 'Last Stage Code', desc: 'Previous stage code' },
    notimeschg: { label: 'Times Changed', desc: 'Number of times changed' },
    ackrsn:     { label: 'Acknowledgment Reason', desc: 'Description: Purchase order acknowledgement reason. Content: AD Accepted without change (VMI or non-VMI) AC Accepted with change (non-VMI)' },
    totlineamt: { label: 'Total Line Amount', desc: 'Total line item amount for the PO' },
  },

  poel: {
    price:      { label: 'Price', desc: 'Unit price for this line item' },
    qtyord:     { label: 'Qty Ordered', desc: 'Quantity ordered' },
    qtyrcv:     { label: 'Qty Received', desc: 'Quantity received' },
    whse:       { label: 'Whse', desc: 'Warehouse ID' },
    shipprod:   { label: 'Ship Product', desc: 'the product (either stocked or non-stocked) for this line item' },
    unit:       { label: 'Unit', desc: 'Unit of measure' },
    duedt:      { label: 'Due Date', desc: 'Line due date' },
    reqshipdt:  { label: 'Requested Ship Date', desc: 'requested ship date represents the date that you originally requested this product from the vendor' },
    statustype: { label: 'Status', desc: 'The status type used for index retrieval purposes. Content: (A)ctive, (I)nactive, (C)ancel, or (S)Costed' },
    glcostinv:  { label: 'GL Cost Invoiced', desc: 'Total GL amt costed for this line item. If partial costing occurred, this field contains the sum of all the partials.' },
    glcostrcv:  { label: 'GL Cost Received', desc: 'GL amount received for this line item' },
    qtycosted:  { label: 'Qty Costed', desc: 'Quantity costed' },
    stkqtybilled: { label: 'Stock Qty Billed', desc: 'Stock quantity billed' },
    buyer:      { label: 'Buyer', desc: 'buyer code as defined in SASTT' },
    ackdt:      { label: 'Acknowledgment Date', desc: 'Purchase order line acknowledgement date.' },
    leadtime:   { label: 'Lead Time', desc: 'lead time of this line item' },
    printfl:    { label: 'Printed', desc: 'Set to yes when a change occurs on the line item that requires a reprint' },
    notimeschg: { label: 'Times Changed', desc: 'number of times this line item has been changed' },
    ackrsn:     { label: 'Acknowledgment Reason', desc: 'Purchase order line acknowledgement reason. Content: (IA) Item accepted (IC) Item accepted, changes made' },
    unitcost:   { label: 'Unit Cost', desc: 'Unit cost for this line item' },
    extcost:    { label: 'Extended Cost', desc: 'Extended cost (unit cost × quantity)' },
    foreigncost: { label: 'Foreign Cost', desc: 'Cost in foreign currency' },
    orderaltcost: { label: 'Order Alt Cost', desc: 'Order alternate cost' },
  },

  // ─── Orders ───

  oeeh: {
    // ── Core Status ──
    stagecd:       { label: 'Stage Code', desc: 'The stage of the order. Content: 0 = Quoted, 1 = Ordered, 2 = Picked, 3 = Shipped, 4 = Invoiced (remains for partial payments), 5 = Paid (in full), 9 = Cancelled' },
    approvty:      { label: 'Approval', desc: 'The approval type of the order. It defaults from the OEAO screen. An order can not be picked until the approval type is set to "y". Content: y = approved, e = e-hold, on hold due to error found when in SXAPI processing, n = not approved, any other character indicates a user defined "hold" status' },
    apprinit:      { label: 'Approval Initials', desc: 'The operator that approved the order (set the approval type to "y"). It is update from OEIR or the order header.' },
    canceldt:      { label: 'Cancel Date', desc: 'The cancel date can be manually entered by an operator. If entered, it indicates that this order must be picked prior to the cancel date or the order will be cancelled. OEEPC or OEEPI will actually cancel the order. NOTE: the cancel date IS NOT set when an order is manually cancelled.' },
    // ── Customer & PO ──
    custno:        { label: 'Customer Number', desc: 'The customer who placed the order.' },
    custpo:        { label: 'Customer PO', desc: 'The customer\'s PO number. This can be established as a unique or non-unique number as defined inside OEAO.' },
    // ── Dates ──
    promisedt:     { label: 'Promise Date', desc: 'The date the order was promised to the customer.' },
    reqshipdt:     { label: 'Requested Ship Date', desc: 'The date the customer requests shipment of the line.' },
    pickeddt:      { label: 'Picked Date', desc: 'The date the pick ticket was last printed.' },
    // ── Shipping ──
    shipviaty:     { label: 'Ship Via', desc: 'This field describes the ship via. It is table driving in SASTT. It describes how the customer would like the goods sent to them' },
    whse:          { label: 'Warehouse', desc: 'The warehouse on the order' },
    frttermscd:    { label: 'Freight Terms', desc: 'Freight Terms. Content: Validated against valid SASTA value' },
    shipto:        { label: 'Ship To', desc: 'The ship to location or job for the customer.' },
    shiptonm:      { label: 'Ship To Name', desc: 'The name of the customer/ship to the order will be sent to.' },
    shiptoaddr_1:  { label: 'Ship To Address 1', desc: 'The shipping address for the order. This defaults from ARSC or ARSS. It can be overridden with the proper security.' },
    shiptoaddr_2:  { label: 'Ship To Address 2', desc: 'Ship-to address 2' },
    shiptoaddr3:   { label: 'Ship To Address 3', desc: 'Ship-to address 3' },
    shiptocity:    { label: 'Ship To City', desc: 'The city the order should be shipped to.' },
    shiptost:      { label: 'Ship To State', desc: 'The state the order will be shipped to.' },
    shiptozip:     { label: 'Ship To Zip', desc: 'The zip code the order will be shipped to.' },
    // ── Financials ──
    termstype:     { label: 'Terms Type', desc: 'The terms defined for this order' },
    totcost:       { label: 'Total Cost', desc: 'The total cost of the order as accumulated from the line items.' },
    totordamt:     { label: 'Total Order Amount', desc: 'An interim value between the totlineamt and the totinvamt.' },
    totlineamt:    { label: 'Total Line Amount', desc: 'This is the total net amount of all line items based on the qty shipped.' },
    totinvamt:     { label: 'Total Invoice Amount', desc: 'The total invoice amount of the order.' },
    taxablefl:     { label: 'Taxable', desc: 'This flag indicates if the customer (order) should be taxed. It defaults from the customer record but can be overridden. Content: yes = this order should be taxed (based on the tax status of entered products) no = no tax should be charged on this order' },
    // ── Quantities ──
    nolineitem:    { label: '# of Lines', desc: 'The number of lines items the match the price type for the found PDSS record. This number is used in OEEPI for proration of the special discount. Each line will get a percentage of the calculated discount until the last line - it will get the remainder. Content: An accumulated number of line items for the price type.' },
    totqtyord:     { label: 'Total Qty Ordered', desc: 'The order ordered stocking quantity for all lines on the order.' },
    totqtyshp:     { label: 'Total Qty Shipped', desc: 'The total stocking quantity that can be/has been shipped on the order.' },
    // ── Personnel ──
    takenby:       { label: 'Taken By', desc: 'The operator that enters the order.' },
    pickinit:      { label: 'Pick Initials', desc: 'The operator that last printed this pick ticket through OEEPP or the demand print (OEETG).' },
    slsrepin:      { label: 'Sales Rep In', desc: 'The inside sales rep on the order.' },
    slsrepout:     { label: 'Sales Rep Out', desc: 'The outside sales rep for the order.' },
    // ── Misc ──
    refer:         { label: 'Reference', desc: 'The order reference.' },
    printpckfl:    { label: 'Reprint Pick Ticket', desc: 'This flag indicates whether the pick ticket needs to be printed or not. When an order is initially added, this flag is set to yes to indicate that a pick ticket does need to be printed. Once printed, this flag is flipped to no. If a line is maintained or added, the printpckfl will again be set to yes to allow a reprint of the pick ticket.' },
    bofl:          { label: 'Backorder Flag', desc: 'Indicates if the customer accepts back orders.' },
    invno:         { label: 'Invoice Number', desc: 'On an RM or CR, the invoice to return against. If an invoice number is entered, it must be an active invoice in ARET. When this order is invoiced, a credit is created against the entered invoice number. NOTE: This is NOT the invoice number of this order. The order number always equates to the invoice number of this particular order.' },
    origorderno:   { label: 'Original Order #', desc: 'The original order number when a standing order (ST) is regenerated.' },
    credoverfl:    { label: 'Credit Override', desc: 'Indicates that the terms or COD status on the order was manually overridden.' },
    // ── User Defined ──
    user1:         { label: 'User Defined 1', desc: 'User defined field' },
    user2:         { label: 'User Defined 2', desc: 'User defined field' },
    user3:         { label: 'User Defined 3', desc: 'User defined field' },
    user4:         { label: 'User Defined 4', desc: 'User defined field' },
    user5:         { label: 'User Defined 5', desc: 'User defined field' },
    user6:         { label: 'User Defined 6', desc: 'User defined field' },
    user7:         { label: 'User Defined 7', desc: 'User defined field' },
    user8:         { label: 'User Defined 8', desc: 'User defined field' },
    user9:         { label: 'User Defined 9', desc: 'User defined field' },
    user10:        { label: 'User Defined 10', desc: 'User defined field' },
    user11:        { label: 'User Defined 11', desc: 'User defined field' },
    user12:        { label: 'User Defined 12', desc: 'User defined field' },
    user13:        { label: 'User Defined 13', desc: 'User defined field' },
    user14:        { label: 'User Defined 14', desc: 'User defined field' },
    user15:        { label: 'User Defined 15', desc: 'User defined field' },
    user16:        { label: 'User Defined 16', desc: 'User defined field' },
    user17:        { label: 'User Defined 17', desc: 'User defined field' },
    user18:        { label: 'User Defined 18', desc: 'User defined field' },
    user19:        { label: 'User Defined 19', desc: 'User defined field' },
    user20:        { label: 'User Defined 20', desc: 'User defined field' },
    user21:        { label: 'User Defined 21', desc: 'User defined field' },
    user22:        { label: 'User Defined 22', desc: 'User defined field' },
    user23:        { label: 'User Defined 23', desc: 'User defined field' },
    user24:        { label: 'User Defined 24', desc: 'User defined field' },
    addressoverfl: { label: 'Address Override', desc: 'Address override flag — indicates the ship-to address was manually changed on this order' },
    ordersource:   { label: 'Order Source', desc: 'Source/origin of the order (e.g. EDI, web, manual entry)' },
  },

  oeel: {
    // ── Core ──
    shipprod:    { label: 'Product', desc: 'This is the primary product on the OE line. It indicates the product that was shipped to the customer (stock or non-stock).If a cross reference product was accessed, it is stored in oeel.reqprod.' },
    prodcat:     { label: 'Product Category', desc: 'The product category of the line item. On a stock product, this field defaults from ICSP. On a non-stock product, it defaults from ICAO. It is overrideable on the extended screen and the non-stock screen. G/L posting can be done by product category.' },
    prodline:    { label: 'Product Line', desc: 'This field represents the source product line for the line item. For a stocked product, it defaults from the ICSL ARP product line (if entered - regardless of the ARP type). For a non-stock product, it is the product line as entered on the non-stock screen. For a special order item, non-stock product, or drop line, this field may duplicate the oeel.arpprodline.' },
    // ── Pricing ──
    price:       { label: 'Price', desc: 'The price of the line item. This field is stored per special costing unit if the product is specially costed. If not, the price is stored per unit on the line item.' },
    netamt:      { label: 'Net Amount', desc: 'The net amount of the line item. This field is used to roll up to the totlineamt on the order. It is the fully extended price and discount of the line. It is calculated by taking the price - discount and multiplying by qtyship.' },
    netord:      { label: 'Net Ordered', desc: 'The extended ordered amount of the line item. This field is used to roll to oeeh.totlineord. This is calculated by taking the price - discount and multiplying by the qtyord.' },
    custcost:    { label: 'Customer Cost', desc: 'The cost of a product that has been identified as customer owned inventory in a storeroom mananged warehouse. Since the customer already owns the inventory, the cost shown on the OE line will be zero. This field tracks the value of the customer owned inventory.' },
    discamt:     { label: 'Discount Amount', desc: 'The discount amount of the line item. This field is represented in the selling unit of measure (if the product is a specially costed product, this field is represented in the special costing unit). The discount amount can be calculated from the PDSC setup (and is thus a % discount). It can also be manually overridden and set to a $ discount.' },
    discpct:     { label: 'Discount %', desc: 'The discount percent on the line item. It can be calculated from the PDSC records or manually entered on a line item. If the discount type is a dollar, the discount percent is still calculated.' },
    disctype:    { label: 'Discount Type', desc: 'The discount type for the line item. It indicates if the discount is a percent or a dollar. Either way, both the discamt and discpct are calculated and stored.' },
    priceoverfl: { label: 'Price Override', desc: 'If this flag is set to yes, it indicates the price has been manually overridden. This will occur when the price is typed in or when previous pricing is done. Content: yes = the price was manually overridden no = the price was not manually overridden' },
    pricetype:   { label: 'Price Type', desc: 'The price type defines a group of products that are similarly priced. This field is used for PDSC level 2, 5, and 8 pricing. It is also used to group products for PDSS pricing.' },
    specprcty:   { label: 'Special Price Type', desc: 'Special pricing type applied to this line item' },
    specnstype:  { label: 'Special/Non-Stock Type', desc: 'The special/non-stock type describes the product/line disposition.' },
    // ── Quantities ──
    qtyord:      { label: 'Qty Ordered', desc: 'The quantity of the product that was requested by the customer. This field is represented in the line item unit of measure.' },
    qtyship:     { label: 'Qty Shipped', desc: 'The quantity that was/will be shipped on the order. It is set to the available quantity when the order is entered and updated from back order fill.' },
    stkqtyord:   { label: 'Stock Qty Ordered', desc: 'The stock quantity ordered indicates how many stocking units have been ordered by the customer.' },
    stkqtyship:  { label: 'Stock Qty Shipped', desc: 'The stock quantity shipped indicates how many stocking units will be/were shipped to the customer.' },
    qtyreturn:   { label: 'Qty Returned', desc: 'The quantity returned on a sales line indicates how many (in stocking units) of the product has been returned. This is updated with a return lines is tied to a sales line (F17 processing from line item entry).' },
    bofl:        { label: 'Backorder', desc: 'Backorder flag for this line' },
    bono:        { label: 'Backorder #', desc: 'The number of the suffix this line was back ordered on. If the bono is 0, a back order has not been generated for the line item (it may be generated in a later stage).' },
    // ── Dates ──
    promisedt:   { label: 'Promise Date', desc: 'The date this line item was promised to the customer' },
    canceldt:    { label: 'Cancelled Date', desc: 'The date the order line was cancelled. During upgrade the field will be loaded with oeel.transdt. This will be the cancel date unless some other program has touched the file since.' },
    reqshipdt:   { label: 'Requested Ship Date', desc: 'The date the customer requests shipment of the line. This field is used at the line level only on a JIT order (OEEH.orderdisp = "j"). The date the customer requests product can be distinguished from the date we promise delivery of the product (OEEL.promisedt).' },
    // ── Warehouse & Shipping ──
    whse:        { label: 'Whse', desc: 'The whse from which product is sold. This field defaults from the banner whse and is not overrideable. It is used to control whse pricing and ICSW updates.' },
    unit:        { label: 'Unit', desc: 'The unit describes the selling unit of measure. It defaults from the ICSW selling unit and can be changed. Validation of the unit in ICSEU or SASTA will set the conversion factor (oeel.unitconv) for the line item.' },
    binloc:      { label: 'Bin Location', desc: 'The bin location for the product. This field is loaded during picking when pick tickets are printed in bin location order.' },
    orderaltno:  { label: 'Related Order #', desc: 'The alternate order number indicates the PO/WT/work order number that the order entry order is tied to. This number is enterable on the extended screen of the line item. If the order is a pick up on the way, drop ship, or tie, the PO/WT number can be automatically generated when go is pressed from the line item. On a pick up on the way or tie line the PO/WT number can also be entered.' },
    ordertype:   { label: 'Order Type', desc: 'The order type of a line tie. This field indicates the source for filling the line item (a PO, WT, or work order).' },
    // ── Cost ──
    vendno:      { label: 'Vendor Number', desc: 'The vendno field describes the source vendor for the line item. On a stocked product, it is loaded from the ICSW ARP vendor (regardless of the ARP type). On a non-stock product, it is loaded from the vendor entered on the non-stock screen. For a special order item, non-stock, or line drop, this field may duplicate oeel.arpvendno.' },
    commcost:    { label: 'Commission Cost', desc: 'The commission cost. This is the product cost used in the commission calculation. It is loaded on the line in OEEPI based on the ICAO settings for commission cost.' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Product Master (ICSP) ───

  icsp: {
    priceonty:   { label: 'Multiplier', desc: 'The Price On Type indicates the standard method of pricing this product to customers. Check dictionary for more info.' },
    unitsell:    { label: 'Selling UOM', desc: 'The selling unit is used as a default for all order entry processes. Check dictionary for more info.' },
    unitstock:   { label: 'Stocking UOM', desc: 'The stocking unit is required for every product. Check dictionary for more info.' },
    prodtype:    { label: 'Product Type', desc: 'Product type. Must be (S)tandard, (R)emanufactured, (I)mplied or Dirty (C)ore' },
    statustype:  { label: 'Status', desc: 'This field determines the status type of the product. Check dictionary for more info.' },
    prodcat:     { label: 'Product Category', desc: 'Product Category. Check dictionary for more info.' },
    weight:      { label: 'Weight', desc: 'Weight is expressed per stocking unit. Check dictionary for more info.' },
    descrip_1:   { label: 'Description 1', desc: 'An array of 2, this holds the primary product description and appears on most reports and inquiries for products. Check dictionary for more info.' },
    descrip_2:   { label: 'Description 2', desc: 'Secondary product description' },
    baseprice:   { label: 'Base Price', desc: 'Base customer price for this product' },
    listprice:   { label: 'List Price', desc: 'Customer list or retail price' },
    prodcost:    { label: 'Product Cost', desc: 'Product cost' },
    stndcost:    { label: 'Standard Cost', desc: 'Standard cost for this product' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
  },

  // ─── Product / Warehouse (ICSW) ───

  icsw: {
    baseprice:   { label: 'Base Price', desc: 'The base price is a customer price for this product in this location. Check dictionary for more info.' },
    listprice:   { label: 'List Price', desc: 'List Price. Customer List or Retail Price. This field is based either on stocking units or special pricing unit. See base price for a complete explanation.' },
    avgcost:     { label: 'Average', desc: 'Average Cost. Check dictionary for more info.' },
    lastcost:    { label: 'Last Cost', desc: 'This field follows the standard cost storage and viewing criteria. Check dictionary for more info.' },
    replcost:    { label: 'Replacement Cost', desc: 'Current replacement cost from the vendor' },
    replcostdt:  { label: 'Replacement Cost Date', desc: 'The date that the replacement cost was last changed' },
    stndcost:    { label: 'Standard Cost', desc: 'Standard cost for this product' },
    orderpt:     { label: 'Min (Order Point)', desc: 'Order Point. Check dictionary for more info.' },
    linept:      { label: 'Max (Line Point)', desc: 'Line Point for ordering controls. Check dictionary for more info.' },
    statustype:  { label: 'Status', desc: 'Status type. Check dictionary for more info.' },
    asqfl:       { label: 'Allow ASQ Calc', desc: 'Allow automatic safety quantity calculation' },
    vendprod:    { label: 'Vendor Product', desc: 'Contains the vendor product field for the ARP Vendno. Additional vendor products may be stored in ICSEC' },
    unitbuy:     { label: 'Buy Unit', desc: 'Standard buying Unit of Measure' },
    pricetype:   { label: 'Price Type', desc: 'Price type for this product in this warehouse' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
  },

  // ─── Customer Master (ARSC) ───

  arsc: {
    // ── Status & Terms ──
    statustype:  { label: 'Status', desc: 'Customer active/inactive status. Yes = Active, No = Inactive' },
    credlim:     { label: 'Credit Limit', desc: 'Credit Limit' },
    termstype:   { label: 'Terms Type', desc: 'Default terms for a OE order. Value is set up in the SASTT function or SASTA table where codeiden = "T"' },
    shipviaty:   { label: 'Ship Via', desc: 'Default Ship Via code for an order' },
    frttermscd:  { label: 'Freight Terms', desc: 'Freight Terms Content: Validated against valid SASTA value - codeiden \'FT\'' },
    inbndfrtfl:  { label: 'Freight Flag In', desc: 'Inbound freight flag' },
    outbndfrtfl: { label: 'Freight Flag Out', desc: 'Outbound freight flag' },
    // ── Assignment ──
    whse:        { label: 'Warehouse', desc: 'Default warehouse for this customer. Primarily used in OE to provide a default warehouse for new orders.' },
    divno:       { label: 'Division #', desc: 'Division number' },
    slsrepout:   { label: 'Sales Rep Out', desc: 'Outside Sales rep to default into the OE order' },
    slsrepin:    { label: 'Sales Rep In', desc: 'Inside Sales rep to default into the OE order' },
    // ── Name & Address ──
    name:        { label: 'Name', desc: 'Customer name' },
    addr_1:      { label: 'Address', desc: 'Customer address line 1' },
    addr_2:      { label: 'Address 2', desc: 'Customer address line 2' },
    addr3:       { label: 'Address 3', desc: 'Customer address line 3' },
    city:        { label: 'City', desc: 'City of the Customer\'s address' },
    state:       { label: 'State', desc: 'State of the customer\'s address' },
    zipcd:       { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:   { label: 'Country', desc: 'Country Code. Blank will default to English' },
    email:       { label: 'Email Address', desc: 'Customer email address' },
    phoneno:     { label: 'Phone', desc: 'Customer phone number' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Customer Ship-To (ARSS) ───

  arss: {
    // ── Status & Terms ──
    statustype:  { label: 'Status', desc: 'Ship-to active/inactive status. A = Active, I = Inactive' },
    credlim:     { label: 'Credit Limit', desc: 'Ship-to credit limit amount' },
    termstype:   { label: 'Terms Type', desc: 'Ship-to payment terms' },
    shipviaty:   { label: 'Ship Via', desc: 'This field describes the ship via.' },
    frttermscd:  { label: 'Freight Terms', desc: 'Freight terms code' },
    inbndfrtfl:  { label: 'Freight Flag In', desc: 'Inbound freight flag' },
    outbndfrtfl: { label: 'Freight Flag Out', desc: 'Outbound freight flag' },
    // ── Assignment ──
    whse:        { label: 'Warehouse', desc: 'Default warehouse for this Ship To.' },
    divno:       { label: 'Division #', desc: 'Division number' },
    slsrepout:   { label: 'Sales Rep Out', desc: 'Outside sales representative' },
    slsrepin:    { label: 'Sales Rep In', desc: 'Internal sales representative' },
    // ── Name & Address ──
    name:        { label: 'Shipto Name', desc: 'Ship-to name' },
    addr_1:      { label: 'Address', desc: 'Ship-to address line 1' },
    addr_2:      { label: 'Address 2', desc: 'Ship-to address line 2' },
    addr3:       { label: 'Address 3', desc: 'Ship-to address line 3' },
    city:        { label: 'City', desc: 'City in which the ship to is located' },
    state:       { label: 'State', desc: 'State code' },
    zipcd:       { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:   { label: 'Country', desc: 'The abbreviation of the country in which the ship to is located' },
    email:       { label: 'Email Address', desc: 'Ship-to email address' },
    phoneno:     { label: 'Phone', desc: 'Ship-to phone number' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Catalog (ICSC) ───

  icsc: {
    // ── Pricing ──
    pricetype:   { label: 'Product Price Type', desc: 'Product pricing method type' },
    priceonty:   { label: 'Price On Type', desc: 'The Price On Type indicates the standard method used to calculate pricing' },
    listprice:   { label: 'List Price', desc: 'List price or retail price' },
    baseprice:   { label: 'Base Price', desc: 'Base price for this catalog entry' },
    prodcost:    { label: 'Replacement Cost', desc: 'Replacement cost for this catalog entry' },
    stndcost:    { label: 'Standard Cost', desc: 'Standard cost for this catalog entry' },
    speccostty:  { label: 'Special Price/Cost', desc: 'Special price or cost type' },
    costmult:    { label: 'Cost Multiplier', desc: 'Cost multiplier used in pricing calculations' },
    costtype:    { label: 'Cost Type', desc: 'Determines how cost is calculated for this catalog entry' },
    rebatety:    { label: 'Rebate Type', desc: 'Rebate type code' },
    rebatecost:  { label: 'Rebate Cost', desc: 'Rebate cost amount' },
    pbseqno:     { label: 'Price Book Sequence #', desc: 'Price book sequence number' },
    // ── Product Info ──
    vendprod:    { label: 'Vendor Part #', desc: 'Vendor product number for this catalog entry' },
    vendno:      { label: 'Vendor #', desc: 'Vendor number' },
    prodline:    { label: 'Vendor Product Line', desc: 'Product line' },
    prodcat:     { label: 'Product Category', desc: 'Product category code' },
    slgroup:     { label: 'Supplier Group', desc: 'Supplier group code' },
    descrip_1:   { label: 'Description', desc: 'Primary description' },
    descrip_2:   { label: 'Description 2', desc: 'Secondary description' },
    descrip3:    { label: 'Extended Description', desc: 'Third product description' },
    // ── UOM & Status ──
    unitstnd:    { label: 'Standard Pack UOM', desc: 'Standard pack unit of measure' },
    unitstock:   { label: 'Stocking UOM', desc: 'Stocking unit of measure' },
    statustype:  { label: 'Status', desc: 'Catalog entry status' },
    eccnclasscd: { label: 'ECCN', desc: 'Export Control Classification Number (ECCN)' },
    serlottype:  { label: 'Extended Type', desc: 'Serial/lot type for this catalog entry' },
    ncnr:        { label: 'Non Cancellable/Non Returnable', desc: 'Non cancellable/non returnable flag' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Transfer Header (WTEH) ───

  wteh: {
    // ── Status ──
    stagecd:     { label: 'Stage Code', desc: 'Stage of the WT. Content: 0 - Requested, 1 - Ordered, 2 - Picked, 3 - Shipped, 4 - Pre, 5 - Exception, 6 - Received, 9 - Cancelled' },
    laststagecd: { label: 'Last Stage Code', desc: 'Previous stage before the current change' },
    reasoncode:  { label: 'Reason Code', desc: 'Reason code for status change' },
    rushfl:      { label: 'Rush', desc: 'If \'Yes\', Then Transfer Will be Processed as a Rush Transfer' },
    // ── Dates ──
    duedt:       { label: 'Due Date', desc: 'Due date for the transfer' },
    reqshipdt:   { label: 'Requested Ship Date', desc: 'Requested ship date' },
    shipdt:      { label: 'Ship Date', desc: 'Date the transfer was shipped' },
    receiptdt:   { label: 'Receipt Date', desc: 'Date the transfer was received' },
    // ── Warehouses & Shipping ──
    shipfmwhse:  { label: 'Ship From Whse', desc: 'Ship from warehouse' },
    shiptowhse:  { label: 'Ship To Whse', desc: 'Ship to warehouse' },
    shipviaty:   { label: 'Ship Via', desc: 'Ship via type' },
    // ── Quantities ──
    totqtyord:   { label: 'Total Qty Ordered', desc: 'Total quantity ordered' },
    totqtyshp:   { label: 'Total Qty Shipped', desc: 'Total quantity shipped' },
    totqtyrcv:   { label: 'Total Qty Received', desc: 'Total quantity received' },
    nolineitem:  { label: '# of Lines', desc: 'Number of line items on the transfer' },
    // ── Personnel ──
    operinit:    { label: 'Operator', desc: 'Operator who made the change' },
    openinit:    { label: 'Opened By', desc: 'Operator who opened the transfer' },
    rcvoperinit: { label: 'Received By', desc: 'Operator who received the transfer' },
    // ── References ──
    orderaltno:  { label: 'Related Order #', desc: 'Related order number' },
    refer:       { label: 'Reference', desc: 'Reference text' },
    // ── Financials (FINANCE tier) ──
    totlineamt:  { label: 'Total Line Amount', desc: 'Total line amount' },
    totordamt:   { label: 'Total Order Amount', desc: 'Total order amount' },
    totshipamt:  { label: 'Total Ship Amount', desc: 'Total shipped amount' },
    totrcvamt:   { label: 'Total Received Amount', desc: 'Total received amount' },
  },

  // ─── Transfer Line (WTEL) ───

  wtel: {
    // ── Status ──
    statustype:  { label: 'Status', desc: '(A)ctive, (S)hipped, (I)nactive, (C)anceled' },
    bofl:        { label: 'Backorder Flag', desc: 'Back order default flag' },
    approveinit: { label: 'Approval', desc: 'Operator who approved the transfer line' },
    approvedt:   { label: 'Approval Date', desc: 'Date the line was approved' },
    approvety:   { label: 'Approval Type', desc: 'Approval type' },
    // ── Product ──
    shipprod:    { label: 'Product', desc: 'Product shipped for this line item.' },
    binloc:      { label: 'Bin Location', desc: 'Bin location in the warehouse' },
    // ── Quantities ──
    qtyord:      { label: 'Qty Ordered', desc: 'Quantity ordered' },
    qtyrcv:      { label: 'Qty Received', desc: 'Quantity received' },
    qtyship:     { label: 'Qty Shipped', desc: 'Quantity shipped' },
    stkqtyord:   { label: 'Stock Qty Ordered', desc: 'Stocking quantity ordered' },
    stkqtyrcv:   { label: 'Stock Qty Received', desc: 'Stocking quantity received' },
    stkqtyship:  { label: 'Stock Qty Shipped', desc: 'Stocking quantity shipped' },
    unit:        { label: 'Unit', desc: 'Unit of measure' },
    // ── Warehouses ──
    shiptowhse:  { label: 'Ship To Whse', desc: 'Ship to warehouse' },
    shipfmwhse:  { label: 'Ship From Whse', desc: 'Ship from warehouse' },
    // ── Dates ──
    duedt:       { label: 'Due Date', desc: 'Line-level due date' },
    // ── Personnel ──
    operinit:    { label: 'Operator', desc: 'Operator who changed the line' },
    // ── Financials (FINANCE tier) ──
    prodcost:    { label: 'Product Cost', desc: 'Product cost of the line item' },
    netamt:      { label: 'Net Amount', desc: 'Net dollar amount for this line' },
    netord:      { label: 'Net Ordered', desc: 'Net ordered amount' },
    netrcv:      { label: 'Net Received', desc: 'Net received amount' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Customer Pricing (PDSC) ───

  pdsc: {
    actqty:        { label: 'Actual Qty', desc: 'the actual qty orders. This field is used in conjunction with pdsc.qtytype to give qty discounts based on year or month' },
    modifierrebfl: { label: 'Allow With Line Rebate', desc: 'Allow with line rebate flag' },
    commtype:      { label: 'Comm Type', desc: 'Commission type' },
    ContractNo:    { label: 'Contract Number', desc: 'Contract number' },
    costmult:      { label: 'Cost Multiplier', desc: 'Cost multiplier' },
    costtype:      { label: 'Cost Type', desc: 'Cost type' },
    enddt:         { label: 'End Date', desc: 'Pricing expiration date' },
    hardmaxqtyfl:  { label: 'Hard Max Qty', desc: 'Hard maximum quantity flag' },
    hardpricefl:   { label: 'Hard Price', desc: 'Hard price flag' },
    qtyyymm:       { label: 'Last CCYYMM for Qty', desc: 'the YYMM of the last order for this odsc record. This field is used with the pdsc.qtytype = m(month) or pdsc.qtytype = y(year) and the pdsc.actqty to identify when a discount by month or year applies' },
    lastuseddt:    { label: 'Last Used Date', desc: 'Last used date' },
    lastuseddttz:  { label: 'Last Used Time', desc: 'Last used time' },
    prcdisc_1:     { label: 'Level 1 Amount discount', desc: 'Level 1 amount discount' },
    prcdisc_2:     { label: 'Level 2 Amount discount', desc: 'Level 2 amount discount' },
    prcdisc_3:     { label: 'Level 3 Amount discount', desc: 'Level 3 amount discount' },
    prcdisc_4:     { label: 'Level 4 Amount discount', desc: 'Level 4 amount discount' },
    prcdisc_5:     { label: 'Level 5 Amount discount', desc: 'Level 5 amount discount' },
    prcdisc_6:     { label: 'Level 6 Amount discount', desc: 'Level 6 amount discount' },
    prcdisc_7:     { label: 'Level 7 Amount discount', desc: 'Level 7 amount discount' },
    prcdisc_8:     { label: 'Level 8 Amount discount', desc: 'Level 8 amount discount' },
    prcdisc_9:     { label: 'Level 9 Amount discount', desc: 'Level 9 amount discount' },
    jobno:         { label: 'Line Refer', desc: 'The job number on the line item. Check dictionary for more info.' },
    maxqtytype:    { label: 'Max Based On', desc: 'Maximum quantity based on type. Quantities are (C)ube, S(p)ecial Prc Cost, (S)tocking Quantity, or (W)eight' },
    maxqty:        { label: 'Maximum Qty', desc: 'Maximum quantity' },
    minqty:        { label: 'Minimum Qty', desc: 'Minimum quantity' },
    modifiernm:    { label: 'Modifier Identifier', desc: 'Modifier identifier name' },
    priceonty:     { label: 'Multiplier', desc: 'Price on type / multiplier. B = base price L = list price M = margin C = cost plus RC = rebate cost RM = rebate margin' },
    disctype:      { label: 'Order Discount Based On', desc: 'specifies the way in which the whole order discount will be applied. Content: Q = quantity D = dollar amount C = customer' },
    ovrridepctdown: { label: 'Override Percent Down', desc: 'The percentage by which any user can ovveride the system price in a downward direction.' },
    ovrridepctup:  { label: 'Override Percent Up', desc: 'The percentage by which any user can ovveride the system price in a upward direction.' },
    prcmult_1:     { label: 'Price Detail Multiplier L1', desc: 'Price detail multiplier level 1' },
    prcmult_2:     { label: 'Price Detail Multiplier L2', desc: 'Price detail multiplier level 2' },
    prcmult_3:     { label: 'Price Detail Multiplier L3', desc: 'Price detail multiplier level 3' },
    prcmult_4:     { label: 'Price Detail Multiplier L4', desc: 'Price detail multiplier level 4' },
    prcmult_5:     { label: 'Price Detail Multiplier L5', desc: 'Price detail multiplier level 5' },
    prcmult_6:     { label: 'Price Detail Multiplier L6', desc: 'Price detail multiplier level 6' },
    prcmult_7:     { label: 'Price Detail Multiplier L7', desc: 'Price detail multiplier level 7' },
    prcmult_8:     { label: 'Price Detail Multiplier L8', desc: 'Price detail multiplier level 8' },
    prcmult_9:     { label: 'Price Detail Multiplier L9', desc: 'Price detail multiplier level 9' },
    prctype:       { label: 'Price Level', desc: 'Indicates the type of price or discount used Content:  true = amount ($) false = percent(%)' },
    pricety:       { label: 'Price Method', desc: 'Price method type' },
    PriceSheet:    { label: 'Price Sheet', desc: 'Price sheet identifier' },
    pround:        { label: 'Pricing - Round', desc: 'Rounding method Content: u = rounds up d = rounds down n = rounds to the nearest' },
    costbasedon:   { label: 'Pricing Cost Based On', desc: 'Pricing cost based on' },
    pricecostty:   { label: 'Pricing Cost Type', desc: 'specifies which type of costing is used. Content: A = average cost S = standard cost L = last cost R = replacement blank = cost taken from the AO settings under IC' },
    prodcost:      { label: 'Product Cost', desc: 'Contains the cost of the product for cost plus and margin calculations if the product is a catalog item' },
    promofl:       { label: 'Promotional', desc: 'Promotional flag indicating that this is a promotion' },
    qtybrk_1:      { label: 'Quantity Break 1', desc: 'Quantity break level 1' },
    qtybrk_2:      { label: 'Quantity Break 2', desc: 'Quantity break level 2' },
    qtybrk_3:      { label: 'Quantity Break 3', desc: 'Quantity break level 3' },
    qtybrk_4:      { label: 'Quantity Break 4', desc: 'Quantity break level 4' },
    qtybrk_5:      { label: 'Quantity Break 5', desc: 'Quantity break level 5' },
    qtybrk_6:      { label: 'Quantity Break 6', desc: 'Quantity break level 6' },
    qtybrk_7:      { label: 'Quantity Break 7', desc: 'Quantity break level 7' },
    qtybrk_8:      { label: 'Quantity Break 8', desc: 'Quantity break level 8' },
    qtybreakty:    { label: 'Quantity Break On', desc: 'Specifies qty break pricing. Content: blank = no qty break pricing p = price (uses pdsc.prcmult array for qty breaks) d = discount (uses pdsc.disc array for qty breaks)' },
    qtytype:       { label: 'Quantity Break Per', desc: 'defines how quantity breaks are established. Content: blank = qty breaks by each order M = qty breaks by month Y = qty break by year' },
    quotefl:       { label: 'Quote', desc: 'Quote flag' },
    quoteno:       { label: 'Quote Number', desc: 'Quote number' },
    refer:         { label: 'Reference', desc: 'Reference' },
    slchgdt:       { label: 'SL Update Date', desc: 'SL update date' },
    slchgdttz:     { label: 'SL Update Time', desc: 'SL update time' },
    stacktrace:    { label: 'Stack Trace', desc: 'Stack trace' },
    statustype:    { label: 'Status', desc: 'Indicates active or inactive record. Content: Yes = active NSo = inactive' },
    ptarget:       { label: 'Target', desc: 'specifies rounding precision. Content: 1 = hundreds, 2 = tens, 3 = ones, 4 = tenths, 5 = hundredths, 6 = thousandths, 7 = ten thousanths, 8 = hundred thousandths, 9 = user defined' },
    termsdiscfl:   { label: 'Terms Discount', desc: 'Terms discount flag' },
    termspct:      { label: 'Terms Discount %', desc: 'Terms discount percentage' },
    user1:         { label: 'User 1', desc: 'User defined field 1' },
    user2:         { label: 'User 2', desc: 'User defined field 2' },
    user3:         { label: 'User 3', desc: 'User defined field 3' },
    user4:         { label: 'User 4', desc: 'User defined field 4' },
    user5:         { label: 'User 5', desc: 'User defined field 5' },
    user6:         { label: 'User 6', desc: 'User defined field 6' },
    user7:         { label: 'User 7', desc: 'User defined field 7' },
    user8:         { label: 'User 8', desc: 'User defined field 8' },
    user9:         { label: 'User 9', desc: 'User defined field 9' },
    pexactrnd:     { label: 'User Tgt', desc: 'User target / exact round. When pdsc.ptarget = 9, this field contains the value (in cents) that the price will end with' },
  },

  // ─── Vendor Pricing (PDSV) ───

  pdsv: {
    buytype:       { label: 'Buy Type', desc: 'The buy type determines the type of breakpoints used to calculate discount by quantity break.' },
    enddt:         { label: 'End Date', desc: 'The ending date for the application of this record. Not every record needs an ending date. Check dictionary for more info.' },
    prcdisc_1:     { label: 'Level 1 Amount discount', desc: 'Level 1 amount discount. Check dictionary for more info.' },
    prcdisc_2:     { label: 'Level 2 Amount discount', desc: 'Level 2 amount discount. Check dictionary for more info.' },
    prcdisc_3:     { label: 'Level 3 Amount discount', desc: 'Level 3 amount discount. Check dictionary for more info.' },
    prcdisc_4:     { label: 'Level 4 Amount discount', desc: 'Level 4 amount discount. Check dictionary for more info.' },
    prcdisc_5:     { label: 'Level 5 Amount discount', desc: 'Level 5 amount discount. Check dictionary for more info.' },
    prcdisc_6:     { label: 'Level 6 Amount discount', desc: 'Level 6 amount discount. Check dictionary for more info.' },
    prcdisc_7:     { label: 'Level 7 Amount discount', desc: 'Level 7 amount discount. Check dictionary for more info.' },
    prcdisc_8:     { label: 'Level 8 Amount discount', desc: 'Level 8 amount discount. Check dictionary for more info.' },
    prcdisc_9:     { label: 'Level 9 Amount discount', desc: 'Level 9 amount discount. Check dictionary for more info.' },
    prcmult_1:     { label: 'Price Detail Multiplier L1', desc: 'Price detail multiplier level 1. Check dictionary for more info.' },
    prcmult_2:     { label: 'Price Detail Multiplier L2', desc: 'Price detail multiplier level 2. Check dictionary for more info.' },
    prcmult_3:     { label: 'Price Detail Multiplier L3', desc: 'Price detail multiplier level 3. Check dictionary for more info.' },
    prcmult_4:     { label: 'Price Detail Multiplier L4', desc: 'Price detail multiplier level 4. Check dictionary for more info.' },
    prcmult_5:     { label: 'Price Detail Multiplier L5', desc: 'Price detail multiplier level 5. Check dictionary for more info.' },
    prcmult_6:     { label: 'Price Detail Multiplier L6', desc: 'Price detail multiplier level 6. Check dictionary for more info.' },
    prcmult_7:     { label: 'Price Detail Multiplier L7', desc: 'Price detail multiplier level 7. Check dictionary for more info.' },
    prcmult_8:     { label: 'Price Detail Multiplier L8', desc: 'Price detail multiplier level 8. Check dictionary for more info.' },
    prcmult_9:     { label: 'Price Detail Multiplier L9', desc: 'Price detail multiplier level 9. Check dictionary for more info.' },
    qtybrk_1:      { label: 'Quantity Break 1', desc: 'Quantity break level 1. Check dictionary for more info.' },
    qtybrk_2:      { label: 'Quantity Break 2', desc: 'Quantity break level 2. Check dictionary for more info.' },
    qtybrk_3:      { label: 'Quantity Break 3', desc: 'Quantity break level 3. Check dictionary for more info.' },
    qtybrk_4:      { label: 'Quantity Break 4', desc: 'Quantity break level 4. Check dictionary for more info.' },
    qtybrk_5:      { label: 'Quantity Break 5', desc: 'Quantity break level 5. Check dictionary for more info.' },
    qtybrk_6:      { label: 'Quantity Break 6', desc: 'Quantity break level 6. Check dictionary for more info.' },
    qtybrk_7:      { label: 'Quantity Break 7', desc: 'Quantity break level 7. Check dictionary for more info.' },
    qtybrk_8:      { label: 'Quantity Break 8', desc: 'Quantity break level 8. Check dictionary for more info.' },
    refer:         { label: 'Reference', desc: 'Standard Trend' },
    slchgdt:       { label: 'SL Update Date', desc: 'SL update date' },
    slchgdttz:     { label: 'SL Update Time', desc: 'SL update time' },
    stacktrace:    { label: 'Stack Trace', desc: 'Stack trace' },
    startdt:       { label: 'Start Date', desc: 'Pricing start date. Check dictionary for more info.' },
    statustype:    { label: 'Status', desc: 'Pricing record status. A = Active, I = Inactive' },
    vendorprice:   { label: 'Vendor Price', desc: 'This field indicates the price to be used either with or without discount. Check dictionary for more info.' },
    user1:         { label: 'User 1', desc: 'User defined field 1' },
    user2:         { label: 'User 2', desc: 'User defined field 2' },
    user3:         { label: 'User 3', desc: 'User defined field 3' },
    user4:         { label: 'User 4', desc: 'User defined field 4' },
    user5:         { label: 'User 5', desc: 'User defined field 5' },
    user6:         { label: 'User 6', desc: 'User defined field 6' },
    user7:         { label: 'User 7', desc: 'User defined field 7' },
    user8:         { label: 'User 8', desc: 'User defined field 8' },
    user9:         { label: 'User 9', desc: 'User defined field 9' },
  },

  // ─── Vendor Master (APSV) ───

  apsv: {
    // ── Status & Terms ──
    statustype:       { label: 'Status', desc: 'Vendor active/inactive status' },
    termstype:        { label: 'Terms Type', desc: 'Default terms for a PO order. Value is set up in the SASTT function or SASTA table where codeiden = \"T\"' },
    paymentty:        { label: 'Payment Terms', desc: 'Payment terms description' },
    shipviaty:        { label: 'Ship Via', desc: 'Ship via type' },
    frttermscd:       { label: 'Freight Terms', desc: 'Freight terms code' },
    freightexpectedty: { label: 'Freight Expected', desc: 'This field indicates whether or not freight is expected for purchase orders from this vendor. Content:  Y = yes N = no "" = yes' },
    fobfl:            { label: 'FOB Destination', desc: 'Free on board destination flag' },
    currencyty:       { label: 'Currency Code', desc: 'Currency type code as defined in SASTC.' },
    // ── Identity ──
    name:             { label: 'Vendor Name', desc: 'Vendor name' },
    lookupnm:         { label: 'Lookup Name', desc: 'Vendor lookup name' },
    vendtype:         { label: 'Vendor Type', desc: 'Vendor type description' },
    apvendcls:        { label: 'Class', desc: 'Vendor classification' },
    proctype:         { label: 'Proc Type', desc: 'Vendor\'s default invoice processing type. E = Expense, T = Trade, A = Third Party Addons' },
    divno:            { label: 'Division', desc: 'This field is used if you are using full divisionalized accounting. Check dictionary for more info.' },
    langcd:           { label: 'Language', desc: 'Language code' },
    // ── Address ──
    addr_1:           { label: 'Address', desc: 'Address line 1' },
    addr_2:           { label: 'Address 2', desc: 'Address line 2' },
    addr3:            { label: 'Address 3', desc: 'Address line 3' },
    city:             { label: 'City', desc: 'City' },
    state:            { label: 'State', desc: 'State code' },
    zipcd:            { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:        { label: 'Country', desc: 'Country abbreviation' },
    // ── Contact ──
    email:            { label: 'Email Address', desc: 'Vendor email' },
    phoneno:          { label: 'Phone', desc: 'Vendor phone number' },
    faxphoneno:       { label: 'Fax Phone', desc: 'Vendor fax number' },
    edi820email:      { label: 'Electronic Remittance Email', desc: 'Electronic remittance email for supplier' },
    // ── Tax & 1099 ──
    fedtaxid:         { label: 'Tax ID #', desc: 'Federal tax ID number' },
    fed1099no:        { label: '1099 Number', desc: '1099 number' },
    fed1099box:       { label: '1099 Type', desc: '1099 box. Check dictionary for more info.' },
    ap1099nm:         { label: '1099 Type Description', desc: 'Contains the name of the 1099 payee. Check dictionary for more info.' },
    resalefl:         { label: 'Resale Flag', desc: 'Resale flag' },
    // ── Banking ──
    bankno:           { label: 'Bank #', desc: 'Bank number' },
    vendbankacct:     { label: 'Bank Account #', desc: 'Vendor bank account number' },
    vendbankacctname: { label: 'Bank Account Name', desc: 'Vendor bank account name' },
    vendbanktrno:     { label: 'Transit Routing #', desc: 'Bank transit routing number' },
    // ── Misc ──
    comment:          { label: 'Comment', desc: 'Vendor comment' },
    dunsno:           { label: 'DUNS #', desc: 'DUNS number' },
    disputevndfl:     { label: 'Dispute', desc: 'Dispute vendor flag' },
    erebtype:         { label: 'Rebates', desc: 'Rebate type' },
    // ── User Defined ──
    user1:            { label: 'User Defined 1', desc: 'User defined field' },
    user2:            { label: 'User Defined 2', desc: 'User defined field' },
    user3:            { label: 'User Defined 3', desc: 'User defined field' },
    user4:            { label: 'User Defined 4', desc: 'User defined field' },
    user5:            { label: 'User Defined 5', desc: 'User defined field' },
    user6:            { label: 'User Defined 6', desc: 'User defined field' },
    user7:            { label: 'User Defined 7', desc: 'User defined field' },
    user8:            { label: 'User Defined 8', desc: 'User defined field' },
    user9:            { label: 'User Defined 9', desc: 'User defined field' },
    user10:           { label: 'User Defined 10', desc: 'User defined field' },
    user11:           { label: 'User Defined 11', desc: 'User defined field' },
    user12:           { label: 'User Defined 12', desc: 'User defined field' },
    user13:           { label: 'User Defined 13', desc: 'User defined field' },
    user14:           { label: 'User Defined 14', desc: 'User defined field' },
    user15:           { label: 'User Defined 15', desc: 'User defined field' },
    user16:           { label: 'User Defined 16', desc: 'User defined field' },
    user17:           { label: 'User Defined 17', desc: 'User defined field' },
    user18:           { label: 'User Defined 18', desc: 'User defined field' },
    user19:           { label: 'User Defined 19', desc: 'User defined field' },
    user20:           { label: 'User Defined 20', desc: 'User defined field' },
    user21:           { label: 'User Defined 21', desc: 'User defined field' },
    user22:           { label: 'User Defined 22', desc: 'User defined field' },
    user23:           { label: 'User Defined 23', desc: 'User defined field' },
    user24:           { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Vendor Ship-From (APSS) ───

  apss: {
    // ── Status & Terms ──
    statustype:       { label: 'Status', desc: 'Ship-from active/inactive status' },
    termstype:        { label: 'Terms Type', desc: 'Ship-from payment terms' },
    shipviaty:        { label: 'Ship Via', desc: 'Ship via type for this ship-from location' },
    frttermscd:       { label: 'Freight Terms', desc: 'Freight terms code' },
    freightexpectedty: { label: 'Freight Expected', desc: 'This field indicates whether or not freight is expected for purchase orders from this vendor and ship from. Content: Y = yes N = no "" = yes' },
    // ── Flags ──
    allowpofl:        { label: 'Allow PO', desc: 'Allow purchase orders flag' },
    bofl:             { label: 'B/O Ok', desc: 'Backorder allowed flag' },
    limitshipvia:     { label: 'Limit Ship Via', desc: 'Limit ship via flag' },
    synccrmfl:        { label: 'Sync To CRM', desc: 'Sync to CRM flag' },
    epotype:          { label: 'Purchase Order Type', desc: 'Identifies the type of output to use when printing purchase orders Content: blank = none e = EDI m = email f = fax' },
    transferloc:      { label: 'Transfer Location', desc: 'Transfer location. Can be used with INCO Terms (frttermscd) for Transfer Location shipping liability.' },
    langcd:           { label: 'Language Code', desc: 'Language code' },
    // ── Name & Address ──
    name:             { label: 'Vendor Name', desc: 'Ship-from name' },
    addr_1:           { label: 'Address', desc: 'Ship-from address line 1' },
    addr_2:           { label: 'Address 2', desc: 'Ship-from address line 2' },
    addr3:            { label: 'Address 3', desc: 'Ship-from address line 3' },
    city:             { label: 'City', desc: 'City' },
    state:            { label: 'State', desc: 'State code' },
    zipcd:            { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:        { label: 'Country', desc: 'Country abbreviation' },
    // ── Contact ──
    email:            { label: 'Email Address', desc: 'Ship-from email' },
    phoneno:          { label: 'Phone', desc: 'Ship-from phone number' },
    faxphoneno:       { label: 'Fax Phone', desc: 'Ship-from fax number' },
    // ── User Defined ──
    user1:            { label: 'User Defined 1', desc: 'User defined field' },
    user2:            { label: 'User Defined 2', desc: 'User defined field' },
    user3:            { label: 'User Defined 3', desc: 'User defined field' },
    user4:            { label: 'User Defined 4', desc: 'User defined field' },
    user5:            { label: 'User Defined 5', desc: 'User defined field' },
    user6:            { label: 'User Defined 6', desc: 'User defined field' },
    user7:            { label: 'User Defined 7', desc: 'User defined field' },
    user8:            { label: 'User Defined 8', desc: 'User defined field' },
    user9:            { label: 'User Defined 9', desc: 'User defined field' },
    user10:           { label: 'User Defined 10', desc: 'User defined field' },
    user11:           { label: 'User Defined 11', desc: 'User defined field' },
    user12:           { label: 'User Defined 12', desc: 'User defined field' },
    user13:           { label: 'User Defined 13', desc: 'User defined field' },
    user14:           { label: 'User Defined 14', desc: 'User defined field' },
    user15:           { label: 'User Defined 15', desc: 'User defined field' },
    user16:           { label: 'User Defined 16', desc: 'User defined field' },
    user17:           { label: 'User Defined 17', desc: 'User defined field' },
    user18:           { label: 'User Defined 18', desc: 'User defined field' },
    user19:           { label: 'User Defined 19', desc: 'User defined field' },
    user20:           { label: 'User Defined 20', desc: 'User defined field' },
    user21:           { label: 'User Defined 21', desc: 'User defined field' },
    user22:           { label: 'User Defined 22', desc: 'User defined field' },
    user23:           { label: 'User Defined 23', desc: 'User defined field' },
    user24:           { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Inventory Transactions (ICET) ───

  icet: {
    // ── Transaction Info ──
    transtype:   { label: 'Transaction Type', desc: 'This field indicates the type of transaction. Check dictionary for more info.' },
    module:      { label: 'Module', desc: 'This represents the Trend module that created the ICET transaction. Check dictionary for more info.' },
    transdt:     { label: 'Transaction Date', desc: 'Records the date when a given record was last changed.' },
    postdt:      { label: 'Post Date', desc: 'The posting date is from the posting date of the journal.' },
    operinit:    { label: 'Operator', desc: 'Tags the record with the login initials of the last operator to update the record.' },
    transproc:   { label: 'Transaction Process', desc: 'The function to last update this record.' },
    // ── Product & Location ──
    prod:        { label: 'Product', desc: 'Product number' },
    whse:        { label: 'Warehouse', desc: 'Warehouse ID' },
    // ── Quantities ──
    stkqtyship:  { label: 'Stock Qty', desc: 'This records the affect on inventory of this particular transaction, up or down. Check dictionary for more info.' },
    qtyunavail:  { label: 'Qty Unavailable', desc: 'Indicates if any of the stockqtyship value will be moved to unavailable' },
    reasunavty:  { label: 'Reason Unavailable', desc: 'If the ICET created results in any quantity unavailable, this field records the reason the stock was placed in unavailable.' },
    // ── References ──
    orderno:     { label: 'Order #', desc: 'The document number from the document that created the ICET.' },
    ordersuf:    { label: 'Order Suffix', desc: 'This is the suffix, if any, for the orderno field.' },
    lineno:      { label: 'Line #', desc: 'Line number' },
    custno:      { label: 'Customer #', desc: 'Related customer number' },
    jrnlno:      { label: 'Journal #', desc: 'Journal number' },
    ticketno:    { label: 'Ticket #', desc: 'Count ticket number' },
    seqno:       { label: 'Sequence #', desc: 'Sequence number' },
    apinvno:     { label: 'AP Invoice #', desc: 'AP invoice number' },
    refer:       { label: 'Reference', desc: 'Trend Standard' },
    divno:       { label: 'Division', desc: 'Division number' },
    phyadjexcp:  { label: 'Physical Adj Exception', desc: 'This field is used to indicate problems or warnings that occured during the posting of physical or cycle count adjustments.' },
    // ── Costs (FINANCE tier) ──
    cost:        { label: 'Cost', desc: 'Transaction cost' },
    origcost:    { label: 'Original Cost', desc: 'Contains the original cost value for a few transactions.' },
    icswcost:    { label: 'Warehouse Cost', desc: 'Warehouse-level cost. Check dictionary for more info.' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
  },

  // ─── Physical Count Detail (ICSEP) ───

  icsep: {
    // ── Count Info ──
    prod:        { label: 'Product', desc: 'Product number' },
    whse:        { label: 'Warehouse', desc: 'Warehouse ID' },
    binloc:      { label: 'Bin Location', desc: 'Bin location in the warehouse' },
    qtycnt:      { label: 'Qty Counted', desc: 'Quantity actually counted' },
    qtyexp:      { label: 'Qty Expected', desc: 'Expected quantity.' },
    operinit:    { label: 'Operator', desc: 'Who performed the count' },
    unit:        { label: 'Unit', desc: 'Unit of measure' },
    inventoryty: { label: 'Inventory Type', desc: 'This field is used to store the whether the adjustment should be made to  customer owned inventory or distributor owned inventory. Check dictionary for more info.' },
    // ── Count Run ──
    runno:       { label: 'Run #', desc: 'The run number field is a primary index, along with cono, warehouse, bin location and product, for this record.' },
    seqno:       { label: 'Sequence #', desc: 'A sequence number indicating the order in which bin locations were added to the count run.' },
    rectype:     { label: 'Record Type', desc: 'This field indicates what type of bin the count record was created for. Check dictionary for more info.' },
    transdt:     { label: 'Transaction Date', desc: 'Records the date when a given record was last changed.' },
    transproc:   { label: 'Transaction Process', desc: 'The function to last update this record.' },
    // ── Flags ──
    lastcntdt:   { label: 'Last Count Date', desc: 'Date this product was last counted' },
    mustcntfl:   { label: 'Must Count', desc: 'Must count flag' },
    entfl:       { label: 'Entered', desc: 'Entry flag' },
    phyfl:       { label: 'Physical', desc: 'Physical count flag' },
    refer:       { label: 'Reference', desc: 'Reference' },
    // ── Costs (FINANCE tier) ──
    cost:        { label: 'Cost', desc: 'Cost at time of count' },
    custcost:    { label: 'Customer Cost', desc: 'Customer cost' },
    custqty:     { label: 'Customer Qty', desc: 'Customer quantity' },
    custqtyunavail: { label: 'Customer Qty Unavailable', desc: 'Customer quantity unavailable' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
  },

  // ─── Count Tickets (ICSET) ───

  icset: {
    // ── Ticket Info ──
    prod:        { label: 'Product', desc: 'Product number' },
    whse:        { label: 'Warehouse', desc: 'Warehouse ID' },
    binloc:      { label: 'Bin Location', desc: 'Bin location' },
    qtycnt:      { label: 'Qty Counted', desc: 'Quantity counted' },
    ticketno:    { label: 'Ticket #', desc: 'Count ticket number' },
    uticketno:   { label: 'User Ticket #', desc: 'User ticket number. Used When Trend Does Not Print Ticket #' },
    operinit:    { label: 'Operator', desc: 'Operator initials' },
    cntoper:     { label: 'Count Operator', desc: 'Operator who performed the count' },
    unit:        { label: 'Unit', desc: 'Unit of measure' },
    // ── Count Run ──
    runno:       { label: 'Run #', desc: 'Count run number' },
    rectype:     { label: 'Record Type', desc: 'This field describes what type of bin the count ticket was created for. Check dictionary for more info.' },
    uncounttype: { label: 'Uncount Type', desc: 'Uncount type' },
    transdt:     { label: 'Last Change Date', desc: 'Records the date when a given record was last changed.' },
    transproc:   { label: 'Transaction Process', desc: 'The function to last update this record.' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
  },

  // ─── Security: SASOO (Operator Setup) ───

  sasoo: {
    arecedbfl:        { label: 'A/R Debits', desc: 'A/R debits flag' },
    notesfl:          { label: 'Access Notes', desc: 'Notes Flag indicating that there are notes associated with this record. Content: * = notes exist ! = Required notes exist blank = no notes exist' },
    promoprcwin:      { label: 'Access OE Promo Price Window', desc: 'Used to determine if the operator can access the promo price window in OE.' },
    secnotefl:        { label: 'Access Secured Notes', desc: 'Access secured notes flag. If \'Yes\', Secured Notes Can be Added, Viewed, and Changed.' },
    catconvertfl:     { label: 'Allow Catalog Stocking', desc: 'Allow Stocking Catalog Items During OE/PO Entry' },
    oenoinvoicefl:    { label: 'Allow For Our Records Only Invoice', desc: 'Allow for our records only invoice' },
    updglapty:        { label: 'Allow GL update AP records', desc: 'Allow GL update AP records' },
    updglarty:        { label: 'Allow GL update AR records', desc: 'Allow GL update AR records' },
    updglicty:        { label: 'Allow GL update IC records', desc: 'Allow GL update IC records' },
    intercofl:        { label: 'Allow InterCo Processing', desc: 'Allow intercompany processing' },
    oeorigpromisefl:  { label: 'Allow Maintenance of Orig Promised Date', desc: 'Allow maintenance of original promised date. Check dictionary for more info.' },
    ncnrfl:           { label: 'Allow NCNR Entry', desc: 'Allow NCNR entry' },
    nscommfl:         { label: 'Allow Non-Stock Comm Type Entry', desc: 'Allow non-stock commission type entry' },
    nonstockfl:       { label: 'Allow Non-Stock Entry', desc: 'Allow non-stock entry' },
    nsquoteoanty:     { label: 'Allow OAN-NS Create in Quote', desc: 'Allow OAN-NS create in quote' },
    oeslsrepfl:       { label: 'Allow OE Salesrep Override', desc: 'Allow sales rep override. Content: I = inside sales rep override O = outside sales rep override B = both inside and outside sales rep override N = No sales rep override allowed' },
    resalefl:         { label: 'Allow PO Non-Resale Entry', desc: 'Allow PO non-resale entry' },
    oetietype:        { label: 'Allow PO,WT,PO&WT,No Ties', desc: 'Allow PO/WT tie type' },
    pocrctfl:         { label: 'Allow Purchase Order Corrections', desc: 'Allow PO corrections' },
    shiptofl:         { label: 'Allow Ship To Address Override', desc: 'Allow ship-to address override' },
    termsoverfl:      { label: 'Allow Terms Override', desc: 'Allow terms override' },
    icacquiredtfl:    { label: 'Allow user to maintain ICSW Acquire Date', desc: 'Controls if the operator has the security to maintain/override the ICSW Acquire Date. Check dictionary for more info.' },
    altoperinit:      { label: 'Alternate Operator', desc: 'Alternate operator' },
    apsuperfl:        { label: 'Ap Supervisor', desc: 'AP supervisor flag' },
    wtapprwhse:       { label: 'Approve WTs for Whse', desc: 'Approve warehouse transfers for warehouse' },
    holdforauthdefault: { label: 'Auth Hold Default', desc: 'Authorization hold default' },
    arwrtofflim:      { label: 'Cash Receipts Writeoff Limit', desc: 'Cash receipts writeoff limit' },
    iccatcrtty:       { label: 'Catalog Create Type', desc: 'This project has not been completed - Company Specific Catalog items. Check dictionary for more info.' },
    chgbalfl:         { label: 'Change Balances', desc: 'Change balances flag' },
    chgglcostfl:      { label: 'Change GL Cost', desc: 'Change GL cost flag' },
    autobillwhsefl:   { label: 'Create OE Billing Orders From WT', desc: 'This gives the operator security to access the WT Billed Order function off the OEET FIle Menu. Check dictionary for more info.' },
    credpostfl:       { label: 'Customer Credits', desc: 'Customer credits posting flag' },
    printernm:        { label: 'Default Printer Name', desc: 'Default printer name' },
    whse:             { label: 'Default Warehouse', desc: 'Home whse for this operator' },
    oedotyamtmax:     { label: 'DO Max Hold Dollar Value', desc: 'This field contains the maximum value for a DO type Order Entry order. Check dictionary for more info.' },
    podotyamtmax:     { label: 'DO Max Hold Dollar Value', desc: 'This field contains the maximum value for a DO type Purchase Order. Check dictionary for more info.' },
    oedotymrgpctmax:  { label: 'DO Max Hold Margin %', desc: 'This field contains the maximum margin percentage for a DO type Order Entry order. Check dictionary for more info.' },
    oedotymrgamtmax:  { label: 'DO Max Hold Margin Amt', desc: 'This field contains the maximum margin value for a DO type Order Entry order. Check dictionary for more info.' },
    oedotyamtmin:     { label: 'DO Min Hold Dollar Value', desc: 'This field contains the minimum value for a DO type Order Entry order. Check dictionary for more info.' },
    podotyamtmin:     { label: 'DO Min Hold Dollar Value', desc: 'This field contains the minimum dollar value for a DO type Purchase Order. Check dictionary for more info.' },
    oedotymrgpctmin:  { label: 'DO Min Hold Margin %', desc: 'This field contains the minimum margin percentage for a DO type Order Entry order. Check dictionary for more info.' },
    oedotymrgamtmin:  { label: 'DO Min Hold Margin Amt', desc: 'This field contains the minimum margin value for a DO type Order Entry order. Check dictionary for more info.' },
    reqtakenfl:       { label: 'Force Taken By Window', desc: 'Force taken by window' },
    gloverfl:         { label: 'GLET Override Flag', desc: 'GLET override flag' },
    oehardprcovrfl:   { label: 'Hard Price Override', desc: 'If the sasoo.oehardprcovrfl is set to no and the pdsp.hardpriceflag is set to yes then the oe line price/discount cannot be changed or repriced.' },
    icmanlistty:      { label: 'ICAMU Manual List Type', desc: 'Types of ICAMU Manual Lists Allowed: (M)anual Product List Only Import (E)xcel Only (B)oth Manual Product List and Excel (N)either Manual Product List is the default' },
    icmassmaintfl:    { label: 'ICAMU Mass Maintenance', desc: 'ICAMU mass maintenance' },
    icmanlistoverfl:  { label: 'ICAMU Override Manual List Operator', desc: 'In ICAMU, allow the user to change the operator intials to review someone elses Manual List.' },
    jmapprvty:        { label: 'JM Prc/Cst Approve Type', desc: 'JM price/cost approve type' },
    jmupdprtpofl:     { label: 'JMEC Allow Printed PO Update', desc: 'JMEC allow printed PO update' },
    kptietype:        { label: 'KP PO/WT Ties', desc: 'KP PO/WT ties type' },
    kpverchg:         { label: 'KP Prev Version Change', desc: 'KP previous version change' },
    kpveruse:         { label: 'KP Prev Version Usage', desc: 'KP previous version usage' },
    limitholdcds:     { label: 'Limit Hold Codes', desc: 'This field is used to manage OE hold security at the approval code level. Check dictionary for more info.' },
    limitslsrepfl:    { label: 'Limit Sales Rep', desc: 'This logical field is used to limit the user\'s security to change OE approval hold codes. Check dictionary for more info.' },
    limittakenbyfl:   { label: 'Limit Taken By', desc: 'This logical field is used to limit the user\'s security to change OE approval hold codes. Check dictionary for more info.' },
    oesotyamtmax:     { label: 'Max Hold Dollar Value', desc: 'This field contains the maximum value for an SO or BR type Order Entry order. Check dictionary for more info.' },
    popotyamtmax:     { label: 'Max Hold Dollar Value', desc: 'This field contains the maximum value for a PO or BR type Purchase Order. Check dictionary for more info.' },
    oesotymrgpctmax:  { label: 'Max Hold Margin %', desc: 'This field contains the maximum margin percentage for an SO or BR type Order Entry order. Check dictionary for more info.' },
    oesotymrgamtmax:  { label: 'Max Hold Margin Amt', desc: 'This field contains the maximum margin amount for an SO or BR type Order Entry order. Check dictionary for more info.' },
    popotyamtmin:     { label: 'Min Hold Dollar Value', desc: 'This field contains the minimum value for a PO or BR type Purchase Order. Check dictionary for more info.' },
    oesotyamtmin:     { label: 'Min Hold Dollar Value', desc: 'This field contains the minimum value for an SO or BR type Order Entry order. Check dictionary for more info.' },
    oesotymrgpctmin:  { label: 'Min Hold Margin %', desc: 'This field contains the minimum margin percentage for an SO or BR type Order Entry order. Check dictionary for more info.' },
    oesotymrgamtmin:  { label: 'Min Hold Margin Amt', desc: 'This field contains the minimum margin amount for an SO or BR type Order Entry order. Check dictionary for more info.' },
    nscrtoanty:       { label: 'OAN-NS Stocking', desc: 'Allow Order As Needed - Non Stock Stocking from OE. Check dictionary for more info.' },
    oechglntypefl:    { label: 'OE Change Line Type', desc: 'If sasoo.oechglntypefl is yes, the operator is allowed to change the line type for an existing line in OE Order Entry. Check dictionary for more info.' },
    oecostoverty:     { label: 'OE Cost Override Type', desc: 'Allow cost override. Check dictionary for more info.' },
    oensqtyshpty:     { label: 'OE NS Ship Qty Override Type', desc: 'This field controls an operator\'s security to be able to change the quantity shipped for a nonstock product on an OE line. Check dictionary for more info.' },
    oeqtyshipty:      { label: 'OE Ship Qty Override Type', desc: 'Qty shipped override. Content: A = allow qty ship override on any order D = allow qty ship decrease only N = do not allow qty ship override' },
    originchangefl:   { label: 'Order Origin Change', desc: 'Indicates whether or not an operator is allowed to modify the order origin code on an existing OE order.' },
    holdintlfl:       { label: 'Override International Hold', desc: 'Override international hold' },
    holdoverfl:       { label: 'Override Order Hold', desc: 'Allow override of Order approval status (oeeh.approvty)' },
    oepricefl:        { label: 'Price/Discount Options', desc: 'Price/discount options' },
    saspgroup:        { label: 'Printer Group', desc: 'Printer group' },
    rprinternm:       { label: 'Receipt Printer', desc: 'Receipt printer' },
    icswstchgfl:      { label: 'Status Copy/Chg For OAN-NS', desc: 'Flag to indicate if the user may change the StatusType field when the product has been set to Order As Needed - Non-Stock. This setting also determines if the user may copy this product to another product.' },
    superfl:          { label: 'Supervisor Status', desc: 'Supervisor status' },
    sysadminfl:       { label: 'System Administrator', desc: 'System administrator flag' },
    oetoleranceovrfl: { label: 'Tolerance Override', desc: 'This indicates if the user may override a system price by more than the override tolerances on the pricing record.' },
    custnotesfl:      { label: 'Update Customer Notes', desc: 'Operator Security Customer Notes' },
    oeupdtcustpofl:   { label: 'Update Customer PO#', desc: 'Allow access to the OEET - Maintain Customer PO function. Located off the File Menu in OEET.' },
    prodnotesfl:      { label: 'Update Product Notes', desc: 'Operator Security on Product Notes' },
    vendnotesfl:      { label: 'Update Vendor Notes', desc: 'Update vendor notes flag' },
    useprevnsfl:      { label: 'Use Previous Non-Stock Settings', desc: 'Use previous non-stock settings' },
    usergroup:        { label: 'User Group', desc: 'User group' },
    logindt:          { label: 'User Last Login Date', desc: 'User last login date' },
    valtakenfl:       { label: 'Validate Taken By', desc: 'Validate taken by flag' },
    vendpostfl:       { label: 'Vendor Returns/Credits', desc: 'Vendor returns/credits posting flag' },
    seecostfl:        { label: 'View Costs', desc: 'View costs flag' },
    xconocostfl:      { label: 'View Cross Cono Costs', desc: 'This option will prevent operators from seeing the cost of a product in another company. Check dictionary for more info.' },
  },

  // ─── Security: PV_USER (User Profile) ───

  pv_user: {
    ActivitySecrLev:          { label: 'Activity Security', desc: 'Contact activity security level.' },
    AOSecurity:               { label: 'Admin Options Security', desc: 'Admin options security' },
    allowbalancegiftfl:       { label: 'Allow Access to Gift Card Balance', desc: 'Allow access to gift card balance' },
    ActivityOtherOperFl:      { label: 'Allow Access to Other Operator Activities', desc: 'Allow access to other operator activities' },
    allowactivategiftfl:      { label: 'Allow Activation of Gift Card', desc: 'Allow activation of gift card' },
    updategltrans:            { label: 'Allow GL Entry Transactions Final Update', desc: 'Allow GL entry transactions final update' },
    nsfoverfl:                { label: 'Allow NSF Fee Override in ARECR', desc: 'Allow NSF fee override in ARECR' },
    seccredmgrfl:             { label: 'Allow Override of Login Credit Mgr', desc: 'This field allows permission to access the File - Credit Manager feature on the Navigator window.' },
    oereassignarfl:           { label: 'Allow Reassign Customer/Ship To', desc: 'Allow reassign customer/ship to' },
    UnlimitedWebAccess:       { label: 'Allow Unlimited Web Access', desc: 'Allow unlimited web access' },
    oeunlinkdotiesfl:         { label: 'Allow Unlink of DO Ties', desc: 'Allow unlink of DO ties' },
    profileuserset:           { label: 'Allow User Specific Settings', desc: 'Allow User Specific Settings When a Profile Is Assigned.' },
    EntryLayout:              { label: 'Allow User to Change Entry Layout', desc: 'Allow user to change entry layout' },
    ChangeProfiles:           { label: 'Allow User to Change Their Profile', desc: 'Allow user to change their profile' },
    apeiusecostfl:            { label: 'Allow User to Chg AP Recon Cost Type', desc: 'Allow user to change AP recon cost type' },
    apeiovertolfl:            { label: 'Allow User to Override Update Tolerances', desc: 'Allow user to override update tolerances' },
    apeiaddonfl:              { label: 'Allow User to Process Addon Invoices', desc: 'Allow user to process addon invoices' },
    apeiexpensefl:            { label: 'Allow User to Process Expense Invoices', desc: 'Allow user to process expense invoices' },
    apeitradefl:              { label: 'Allow User to Process Trade Invoices', desc: 'Allow user to process trade invoices' },
    restricteditapfl:         { label: 'Allowed Editing of Restricted Editing AP Records', desc: 'Allowed editing of restricted AP records' },
    restricteditarfl:         { label: 'Allowed Editing of Restricted Editing AR Records', desc: 'Allowed editing of restricted AR records' },
    ContactMgmntSecrLev:      { label: 'Contact Management Security', desc: 'Security level for contact management. Content: 1 = no access 2 = inquiry 3 = modify 4 = add 5 = delete' },
    Disabled:                 { label: 'Disabled', desc: 'indicates that the account is disabled. This field is set by the radio set on the "Login" area of page 2 of the GUI SASOO function' },
    webextensiontype:         { label: 'Extension Access Level', desc: 'Extension access level' },
    oeprodtypecostoverty:     { label: 'Product Type Cost Override', desc: 'Product type cost override' },
    reqdraweridfl:            { label: 'Require Drawer ID', desc: 'Require drawer ID flag' },
    divnorestrictapfl:        { label: 'Restrict Data Access For AP', desc: 'Restrict data access for AP' },
    divnorestrictarfl:        { label: 'Restrict Data Access For AR', desc: 'Restrict data access for AR' },
    divnorestrictcrfl:        { label: 'Restrict Data Access For CR', desc: 'Restrict data access for CR' },
    divnorestrictglfl:        { label: 'Restrict Data Access For GL', desc: 'Restrict data access for GL' },
    divnorestricticfl:        { label: 'Restrict Data Access For IC', desc: 'Restrict data access for IC' },
    divnorestrictoefl:        { label: 'Restrict Data Access For OE', desc: 'Restrict data access for OE' },
    divnorestrictpofl:        { label: 'Restrict Data Access For PO', desc: 'Restrict data access for PO' },
    divnorestrictwtfl:        { label: 'Restrict Data Access For WT', desc: 'Restrict data access for WT' },
    divnorestrictwtallfl:     { label: 'Restrict Data Access For WT-Allow Across Divisions', desc: 'Restrict data access for WT allow across divisions' },
    pdrestrictty:             { label: 'Restrict Pricing And Price Sheets', desc: 'Restrict pricing and price sheets' },
    twlrestrictwhsefl:        { label: 'Restrict to TWL Warehouse Only', desc: 'Restrict to TWL warehouse only' },
    rolename:                 { label: 'Role Name', desc: 'Role name' },
    webmodificationaccesslevel: { label: 'Save/Load Web Modifications', desc: 'Save/load web modifications access level' },
    websettingaccesslevel:    { label: 'Save/Load Web Settings', desc: 'Save/load web settings access level' },
    UserName:                 { label: 'User Name', desc: 'User name' },
    ProfileName:              { label: 'User Profile', desc: 'This field is currently formatted as 12 characters. This field can hold operator initials or profile names (cono = 0). When loaded with a profile name, the field maps to the pvregistry.oper field, which is formatted to 12 characters.' },
    oevendcontaccesscd:       { label: 'Vendor Contract Pricing Access for Order Entry', desc: 'Vendor contract pricing access for OE' },
    povendcontaccesscd:       { label: 'Vendor Contract Pricing Access for Purchasing', desc: 'Vendor contract pricing access for purchasing' },
    viewcosttype:             { label: 'View Cost Type Override', desc: 'View cost type override' },
    webprofilename:           { label: 'WebUI User Profile', desc: 'WebUI user profile name' },
  },

  // ─── Security: PV_SECURE (Function Security) ───

  pv_secure: {
    FunctionSecurity:  { label: 'Function Security', desc: 'containers the security level for the function in functionname. Content: 1 = no access 2 = Inquiry only 3 = Modify 4 = Add & modify 5 = add, modify and delete' },
    FolderDelimiter:   { label: 'Folder Delimiter', desc: 'Folder delimiter' },
    MenuSet:           { label: 'Menu Set', desc: 'Menu set' },
  },

  // ─── Security: AUTHSECURE (Authorization Security) ───

  authsecure: {
    action_datetime:  { label: 'Action Datetime', desc: 'Action datetime' },
    actionby:         { label: 'Action Taken By', desc: 'Operator that authorized or denied the transaction.' },
    authtransid:      { label: 'Authtrans Recid', desc: 'Authorization transaction record ID' },
    ourproc:          { label: 'Function', desc: 'Function/process' },
    key1:             { label: 'Key 1', desc: 'Key 1' },
    key2:             { label: 'Key 2', desc: 'Key 2' },
    mode:             { label: 'Mode', desc: 'Mode' },
    securcd:          { label: 'Securcd', desc: 'Security code' },
    authstatus:       { label: 'Status', desc: 'Authorization status' },
    transtype:        { label: 'Type', desc: 'Transaction type' },
  },
};

/**
 * Get tracked fields for a table. Returns empty object if table not registered.
 */
function getTrackedFields(table) {
  return TRACKED_FIELDS[table.toLowerCase()] || {};
}

/**
 * Get table config (key field names). Returns default pono/posuf if not registered.
 */
function getTableConfig(table) {
  return TABLE_CONFIG[table.toLowerCase()] || { recordKey: 'pono', suffixKey: 'posuf', lineKey: null };
}

module.exports = {
  TRACKED_FIELDS,
  TABLE_CONFIG,
  getTrackedFields,
  getTableConfig,
};
