/**
 * Tracked Fields Registry
 *
 * Defines which fields to track for each Data Lake table, plus
 * metadata about how each table's primary key maps to generic
 * search filters (recordno/recordsuf).
 *
 * To add a new module:
 *   1. Add TABLE_CONFIG entries for each table
 *   2. Add TRACKED_FIELDS entries for each table
 *   3. Add field definitions to server/tracked-fields.js (this file)
 *   4. Create a new page in src/pages/
 */

// ─── Table Configuration ───
// Maps each table's primary key columns so the generic search
// (which sends pono/posuf from the frontend) gets translated
// to the correct column names in the SQL query.

const TABLE_CONFIG = {
  // Purchases
  poeh:  { recordKey: 'pono', suffixKey: 'posuf', lineKey: null, recordKeyType: 'number' },
  poel:  { recordKey: 'pono', suffixKey: 'posuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Orders
  oeeh:  { recordKey: 'orderno', suffixKey: 'ordersuf', lineKey: null, recordKeyType: 'number' },
  oeel:  { recordKey: 'orderno', suffixKey: 'ordersuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Product / Warehouse
  icsp:  { recordKey: 'prod', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  icsw:  { recordKey: 'prod', suffixKey: null, lineKey: 'whse', recordKeyType: 'string' },

  // Customers
  arsc:  { recordKey: 'custno', suffixKey: null, lineKey: null, recordKeyType: 'number' },
  arss:  { recordKey: 'custno', suffixKey: null, lineKey: 'shipto', recordKeyType: 'number' },

  // Catalog
  icsc:  { recordKey: 'catalog', suffixKey: null, lineKey: null, recordKeyType: 'string' },

  // Transfers
  wteh:  { recordKey: 'wtno', suffixKey: 'wtsuf', lineKey: null, recordKeyType: 'number' },
  wtel:  { recordKey: 'wtno', suffixKey: 'wtsuf', lineKey: 'lineno', recordKeyType: 'number' },

  // Customer Pricing
  pdsc:  { recordKey: 'pdrecno', suffixKey: null, lineKey: null, recordKeyType: 'number' },

  // Vendor Pricing
  pdsv:  { recordKey: 'vendno', suffixKey: null, lineKey: 'prod', recordKeyType: 'number' },

  // Vendors
  apsv:  { recordKey: 'vendno', suffixKey: null, lineKey: null, recordKeyType: 'number' },
  apss:  { recordKey: 'vendno', suffixKey: null, lineKey: 'shipfmno', recordKeyType: 'number' },

  // Security
  sasoo:       { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  pv_user:     { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string' },
  pv_secure:   { recordKey: 'oper2', suffixKey: null, lineKey: 'FunctionName', recordKeyType: 'string' },
  authsecure:  { recordKey: 'oper2', suffixKey: null, lineKey: null, recordKeyType: 'string', groupFields: ['oper2', 'ourproc', 'key1'] },
};

// ─── Tracked Fields ───
// Each entry: { label: 'Display Name', desc: 'Description for expanded row' }

const TRACKED_FIELDS = {

  // ─── Purchases ───

  poeh: {
    stagecd:    { label: 'Stage Code', desc: 'the stage of the PO. Content: 0 - Entered, 1 - Ordered, 2 - Printed, 3 - Acknowledged, 5 - Received, 7 - Costed, 9 - Closed' },
    approvty:   { label: 'Approval', desc: '(Y)es, (N)o or Any Other Character for Hold' },
    duedt:      { label: 'Due Date', desc: 'Category In' },
    expshipdt:  { label: 'Expected Ship Date', desc: 'Expected ship date' },
    reqshipdt:  { label: 'Requested Ship Date', desc: 'Requested Ship Date is the date that you have requested the shipment' },
    frttermscd: { label: 'Freight Terms', desc: 'Freight Terms. Content: Validated against valid SASTA value - carrier freight terms' },
    termstype:  { label: 'Terms Type', desc: 'Default terms comes from apsv.termstype. Value is set up in the Terms table' },
    shipviaty:  { label: 'Ship Via', desc: 'Ship via type' },
    buyer:      { label: 'Buyer', desc: 'Buyer operator code' },
    whse:       { label: 'Warehouse', desc: 'Warehouse ID' },
    vendno:     { label: 'Vendor Number', desc: 'Vendor number' },
    refer:      { label: 'Reference', desc: 'Reference' },
    vendordno:  { label: 'Vendor Order Number', desc: 'Vendor order number' },
    receiptdt:  { label: 'Receipt Date', desc: 'Date the PO was received' },
    rcvoperinit: { label: 'Received By', desc: 'Operator who received the PO' },
    costeddt:   { label: 'Costed Date', desc: 'Date the PO was costed' },
    paiddt:     { label: 'Paid Date', desc: 'Date the PO was paid' },
    printeddt:  { label: 'Printed Date', desc: 'Date the PO was printed' },
    printfl:    { label: 'Printed', desc: 'PO print flag' },
    totinvamt:  { label: 'Total Invoice Amount', desc: 'Total invoice amount' },
    totuinvamt: { label: 'Total Uninvoiced Amount', desc: 'Total uninvoiced amount' },
    totqtycost: { label: 'Total Qty Cost', desc: 'Total quantity cost' },
    jrnlno:     { label: 'Journal Number', desc: 'GL journal number' },
    ackdt:      { label: 'Acknowledgment Date', desc: 'Vendor acknowledgment date' },
    ackoper:    { label: 'Acknowledged By', desc: 'Operator who acknowledged' },
    acktype:    { label: 'Acknowledgment Type', desc: 'Acknowledgment type' },
    countrycd:  { label: 'Country', desc: 'Country code' },
    dueoverfl:  { label: 'Due Date Override', desc: 'Due date override flag' },
    glupdfl:    { label: 'GL Updated', desc: 'GL updated flag' },
    laststagecd: { label: 'Last Stage Code', desc: 'Previous stage code' },
    notimeschg: { label: 'Times Changed', desc: 'Number of times changed' },
    ackrsn:     { label: 'Acknowledgment Reason', desc: 'Acknowledgment reason' },
    stacktrace: { label: 'Stack Trace', desc: 'Stack trace' },
  },

  poel: {
    price:      { label: 'Price', desc: 'Unit price for this line item' },
    qtyord:     { label: 'Qty Ordered', desc: 'Quantity ordered' },
    qtyrcv:     { label: 'Qty Received', desc: 'Quantity received' },
    whse:       { label: 'Whse', desc: 'Warehouse ID' },
    shipprod:   { label: 'Ship Product', desc: 'Shipped product' },
    unit:       { label: 'Unit', desc: 'Unit of measure' },
    duedt:      { label: 'Due Date', desc: 'Line due date' },
    reqshipdt:  { label: 'Requested Ship Date', desc: 'Requested ship date' },
    statustype: { label: 'Status', desc: 'Line status (a=active, i=inactive)' },
    glcostinv:  { label: 'GL Cost Invoiced', desc: 'GL cost at invoicing' },
    glcostrcv:  { label: 'GL Cost Received', desc: 'GL cost at receiving' },
    qtycosted:  { label: 'Qty Costed', desc: 'Quantity costed' },
    stkqtybilled: { label: 'Stock Qty Billed', desc: 'Stock quantity billed' },
    buyer:      { label: 'Buyer', desc: 'Buyer operator code' },
    ackdt:      { label: 'Acknowledgment Date', desc: 'Vendor acknowledgment date' },
    leadtime:   { label: 'Lead Time', desc: 'Lead time in days' },
    printfl:    { label: 'Printed', desc: 'Line print flag' },
    notimeschg: { label: 'Times Changed', desc: 'Number of times changed' },
    ackrsn:     { label: 'Acknowledgment Reason', desc: 'Acknowledgment reason' },
    stacktrace: { label: 'Stack Trace', desc: 'Stack trace' },
  },

  // ─── Orders ───

  oeeh: {
    // ── Core Status ──
    stagecd:       { label: 'Stage Code', desc: 'the stage of the order. Content: 0 - Quoted, 1 - Ordered, 2 - Picked, 3 - Shipped, 4 - Invoiced (remains for partial payments), 5 - Paid (in full), 9 - Cancelled' },
    approvty:      { label: 'Approval', desc: '(Y)es, (N)o or Any Other Character for Hold' },
    apprinit:      { label: 'Approval Initials', desc: 'Initials of person who approved the order' },
    canceldt:      { label: 'Cancel Date', desc: 'Date the order was cancelled' },
    // ── Customer & PO ──
    custno:        { label: 'Customer Number', desc: 'Customer number' },
    custpo:        { label: 'Customer PO', desc: 'Customer purchase order number' },
    // ── Dates ──
    promisedt:     { label: 'Promise Date', desc: 'Date promised to the customer' },
    reqshipdt:     { label: 'Requested Ship Date', desc: 'Requested ship date from the customer' },
    pickeddt:      { label: 'Picked Date', desc: 'Date the order was picked' },
    // ── Shipping ──
    shipviaty:     { label: 'Ship Via', desc: 'Ship via type' },
    whse:          { label: 'Warehouse', desc: 'Warehouse ID' },
    frttermscd:    { label: 'Freight Terms', desc: 'Freight Terms. Content: Validated against valid SASTA value' },
    shipto:        { label: 'Ship To', desc: 'Ship-to number' },
    shiptonm:      { label: 'Ship To Name', desc: 'Ship-to customer name' },
    shiptoaddr_1:  { label: 'Ship To Address 1', desc: 'Ship-to address line 1' },
    shiptoaddr_2:  { label: 'Ship To Address 2', desc: 'Ship-to address line 2' },
    shiptoaddr3:   { label: 'Ship To Address 3', desc: 'Ship-to address line 3' },
    shiptocity:    { label: 'Ship To City', desc: 'Ship-to city' },
    shiptost:      { label: 'Ship To State', desc: 'Ship-to state' },
    shiptozip:     { label: 'Ship To Zip', desc: 'Ship-to zip code' },
    addressoverfl: { label: 'Address Override', desc: 'Address override flag' },
    // ── Financials ──
    termstype:     { label: 'Terms Type', desc: 'Default terms. Value is set up in the Terms table' },
    totcost:       { label: 'Total Cost', desc: 'Total cost of the order' },
    totordamt:     { label: 'Total Order Amount', desc: 'Total order amount' },
    totlineamt:    { label: 'Total Line Amount', desc: 'Total line item amount' },
    totinvamt:     { label: 'Total Invoice Amount', desc: 'Total invoiced amount' },
    taxablefl:     { label: 'Taxable', desc: 'Taxable flag' },
    // ── Quantities ──
    nolineitem:    { label: '# of Lines', desc: 'Number of line items on the order' },
    totqtyord:     { label: 'Total Qty Ordered', desc: 'Total quantity ordered' },
    totqtyshp:     { label: 'Total Qty Shipped', desc: 'Total quantity shipped' },
    // ── Personnel ──
    takenby:       { label: 'Taken By', desc: 'Operator who took the order' },
    pickinit:      { label: 'Pick Initials', desc: 'Initials of the picker' },
    slsrepin:      { label: 'Sales Rep In', desc: 'Inside sales rep' },
    slsrepout:     { label: 'Sales Rep Out', desc: 'Outside sales rep' },
    // ── Misc ──
    refer:         { label: 'Reference', desc: 'Reference' },
    printpckfl:    { label: 'Reprint Pick Ticket', desc: 'Reprint pick ticket flag' },
    bofl:          { label: 'Backorder Flag', desc: 'Allow backorders flag' },
    invno:         { label: 'Invoice Number', desc: 'Invoice number' },
    origorderno:   { label: 'Original Order #', desc: 'Original order number if copied/converted' },
    ordersource:   { label: 'Order Source', desc: 'Source/origin of the order' },
    credoverfl:    { label: 'Credit Override', desc: 'Credit limit override flag' },
    // ── User Defined ──
    user1:         { label: 'User Defined 1', desc: 'User defined field' },
    user2:         { label: 'User Defined 2', desc: 'User defined field' },
    user3:         { label: 'User Defined 3', desc: 'User defined field' },
    user4:         { label: 'User Defined 4', desc: 'User defined field' },
    user5:         { label: 'User Defined 5', desc: 'User defined field' },
    user6:         { label: 'User Defined 6', desc: 'User defined field' },
    user7:         { label: 'User Defined 7', desc: 'User defined field' },
    user8:         { label: 'User Defined 8', desc: 'User defined field' },
    user9:         { label: 'User Defined 9', desc: 'User defined field' },
    user10:        { label: 'User Defined 10', desc: 'User defined field' },
    user11:        { label: 'User Defined 11', desc: 'User defined field' },
    user12:        { label: 'User Defined 12', desc: 'User defined field' },
    user13:        { label: 'User Defined 13', desc: 'User defined field' },
    user14:        { label: 'User Defined 14', desc: 'User defined field' },
    user15:        { label: 'User Defined 15', desc: 'User defined field' },
    user16:        { label: 'User Defined 16', desc: 'User defined field' },
    user17:        { label: 'User Defined 17', desc: 'User defined field' },
    user18:        { label: 'User Defined 18', desc: 'User defined field' },
    user19:        { label: 'User Defined 19', desc: 'User defined field' },
    user20:        { label: 'User Defined 20', desc: 'User defined field' },
    user21:        { label: 'User Defined 21', desc: 'User defined field' },
    user22:        { label: 'User Defined 22', desc: 'User defined field' },
    user23:        { label: 'User Defined 23', desc: 'User defined field' },
    user24:        { label: 'User Defined 24', desc: 'User defined field' },
  },

  oeel: {
    // ── Core ──
    shipprod:    { label: 'Product', desc: 'The primary product on the OE line. Indicates the product shipped to the customer (stock or non-stock)' },
    prodcat:     { label: 'Product Category', desc: 'Product category code' },
    prodline:    { label: 'Product Line', desc: 'Product line' },
    // ── Pricing ──
    price:       { label: 'Price', desc: 'The price of the line item. Stored per special cost/unit if the product is specially costed, otherwise per unit on the line item' },
    netamt:      { label: 'Net Amount', desc: 'Net dollar amount for this line' },
    netord:      { label: 'Net Ordered', desc: 'Net ordered amount' },
    custcost:    { label: 'Customer Cost', desc: 'Customer cost for this line' },
    discamt:     { label: 'Discount Amount', desc: 'Discount amount on the line' },
    discpct:     { label: 'Discount %', desc: 'Discount percentage' },
    disctype:    { label: 'Discount Type', desc: 'Discount type' },
    priceoverfl: { label: 'Price Override', desc: 'Price override flag' },
    pricetype:   { label: 'Price Type', desc: 'Price type indicator' },
    specprcty:   { label: 'Special Price Type', desc: 'Special pricing type' },
    specnstype:  { label: 'Special/Non-Stock Type', desc: 'Special or non-stock product type' },
    // ── Quantities ──
    qtyord:      { label: 'Qty Ordered', desc: 'Quantity ordered on this line' },
    qtyship:     { label: 'Qty Shipped', desc: 'Quantity shipped on this line' },
    stkqtyord:   { label: 'Stock Qty Ordered', desc: 'Stocking quantity ordered' },
    stkqtyship:  { label: 'Stock Qty Shipped', desc: 'Stocking quantity shipped' },
    qtyreturn:   { label: 'Qty Returned', desc: 'Quantity returned' },
    bofl:        { label: 'Backorder', desc: 'Backorder flag for this line' },
    bono:        { label: 'Backorder #', desc: 'Backorder number' },
    // ── Dates ──
    promisedt:   { label: 'Promise Date', desc: 'The date this line item was promised to the customer' },
    canceldt:    { label: 'Cancelled Date', desc: 'The date the order line was cancelled' },
    reqshipdt:   { label: 'Requested Ship Date', desc: 'Requested ship date for this line' },
    // ── Warehouse & Shipping ──
    whse:        { label: 'Whse', desc: 'Warehouse ID for this line' },
    unit:        { label: 'Unit', desc: 'Unit of measure' },
    binloc:      { label: 'Bin Location', desc: 'Bin location in the warehouse' },
    orderaltno:  { label: 'Related Order #', desc: 'The related order number - contains the orderno, wtno, vano, or whse transfer number' },
    ordertype:   { label: 'Order Type', desc: 'Order type for this line' },
    // ── Cost ──
    vendno:      { label: 'Vendor Number', desc: 'Vendor number for this line' },
    commcost:    { label: 'Commission Cost', desc: 'Commissionable cost' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Product Master (ICSP) ───

  icsp: {
    priceonty:   { label: 'Multiplier', desc: 'The Price On Type indicates the standard method used to calculate pricing for this product' },
    unitsell:    { label: 'Selling UOM', desc: 'The selling unit is used as a default for all order entry' },
    unitstock:   { label: 'Stocking UOM', desc: 'The stocking unit of measure for this product' },
    prodtype:    { label: 'Product Type', desc: 'Product type. S = Stock, N = Non-Stock, D = Direct Ship' },
    statustype:  { label: 'Status', desc: 'Status type. This field is used in conjunction with Product Type to control product behavior' },
    prodcat:     { label: 'Product Category', desc: 'Product category code' },
    weight:      { label: 'Weight', desc: 'Product weight' },
    descrip_1:   { label: 'Description 1', desc: 'Primary product description' },
    descrip_2:   { label: 'Description 2', desc: 'Secondary product description' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
  },

  // ─── Product / Warehouse (ICSW) ───

  icsw: {
    baseprice:   { label: 'Base Price', desc: 'The base price is a customer price for this product' },
    listprice:   { label: 'List Price', desc: 'List Price. Customer List or Retail Price. This is typically the manufacturer suggested retail price' },
    avgcost:     { label: 'Average', desc: 'Average Cost. This field is maintained by the system based on receiving activity' },
    lastcost:    { label: 'Last Cost', desc: 'Last cost paid for this product' },
    replcost:    { label: 'Replacement Cost', desc: 'Current replacement cost from the vendor' },
    replcostdt:  { label: 'Replacement Cost Date', desc: 'The date that the replacement cost was last changed' },
    stndcost:    { label: 'Standard Cost', desc: 'Standard cost for this product' },
    orderpt:     { label: 'Min (Order Point)', desc: 'Order Point. This is the basic quantity used by the system to determine when to reorder' },
    linept:      { label: 'Max (Line Point)', desc: 'Line Point for ordering controls. For most ordering methods this represents the maximum stocking level' },
    statustype:  { label: 'Status', desc: 'Status type. This field is used in conjunction with Product Type to control product behavior' },
    asqfl:       { label: 'Allow ASQ Calc', desc: 'Allow automatic safety quantity calculation' },
    vendprod:    { label: 'Vendor Product', desc: 'Vendor product number' },
    unitbuy:     { label: 'Buy Unit', desc: 'Unit of measure for purchasing' },
    pricetype:   { label: 'Price Type', desc: 'Price type for this product in this warehouse' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
  },

  // ─── Customer Master (ARSC) ───

  arsc: {
    // ── Status & Terms ──
    statustype:  { label: 'Status', desc: 'Customer active/inactive status' },
    credlim:     { label: 'Credit Limit', desc: 'Customer credit limit amount' },
    termstype:   { label: 'Terms Type', desc: 'Customer payment terms' },
    shipviaty:   { label: 'Ship Via', desc: 'This field describes the ship via. It is table driving in the Ship Via table (SA)' },
    frttermscd:  { label: 'Freight Terms', desc: 'Freight terms code' },
    inbndfrtfl:  { label: 'Freight Flag In', desc: 'Inbound freight flag' },
    outbndfrtfl: { label: 'Freight Flag Out', desc: 'Outbound freight flag' },
    // ── Assignment ──
    whse:        { label: 'Warehouse', desc: 'Default warehouse for this customer' },
    divno:       { label: 'Division #', desc: 'Division number' },
    slsrepout:   { label: 'Sales Rep Out', desc: 'External sales representative' },
    slsrepin:    { label: 'Sales Rep In', desc: 'Internal sales representative' },
    // ── Name & Address ──
    name:        { label: 'Name', desc: 'Customer name' },
    addr_1:      { label: 'Address', desc: 'Customer address line 1' },
    addr_2:      { label: 'Address 2', desc: 'Customer address line 2' },
    addr3:       { label: 'Address 3', desc: 'Third address line used for international addresses' },
    city:        { label: 'City', desc: 'City in which the customer is located' },
    state:       { label: 'State', desc: 'State code' },
    zipcd:       { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:   { label: 'Country', desc: 'The abbreviation of the country' },
    email:       { label: 'Email Address', desc: 'Customer email address' },
    phoneno:     { label: 'Phone', desc: 'Customer phone number' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Customer Ship-To (ARSS) ───

  arss: {
    // ── Status & Terms ──
    statustype:  { label: 'Status', desc: 'Ship-to active/inactive status' },
    credlim:     { label: 'Credit Limit', desc: 'Ship-to credit limit amount' },
    termstype:   { label: 'Terms Type', desc: 'Ship-to payment terms' },
    shipviaty:   { label: 'Ship Via', desc: 'This field describes the ship via. It is table driving in the Ship Via table' },
    frttermscd:  { label: 'Freight Terms', desc: 'Freight terms code' },
    inbndfrtfl:  { label: 'Freight Flag In', desc: 'Inbound freight flag' },
    outbndfrtfl: { label: 'Freight Flag Out', desc: 'Outbound freight flag' },
    // ── Assignment ──
    whse:        { label: 'Warehouse', desc: 'Default warehouse for this ship-to' },
    divno:       { label: 'Division #', desc: 'Division number' },
    slsrepout:   { label: 'Sales Rep Out', desc: 'External sales representative' },
    slsrepin:    { label: 'Sales Rep In', desc: 'Internal sales representative' },
    // ── Name & Address ──
    name:        { label: 'Shipto Name', desc: 'Ship-to name' },
    addr_1:      { label: 'Address', desc: 'Ship-to address line 1' },
    addr_2:      { label: 'Address 2', desc: 'Ship-to address line 2' },
    addr3:       { label: 'Address 3', desc: 'Third address line used for international addresses' },
    city:        { label: 'City', desc: 'City in which the ship to is located' },
    state:       { label: 'State', desc: 'State code' },
    zipcd:       { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:   { label: 'Country', desc: 'The abbreviation of the country in which the ship to is located' },
    email:       { label: 'Email Address', desc: 'Ship-to email address' },
    phoneno:     { label: 'Phone', desc: 'Ship-to phone number' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Catalog (ICSC) ───

  icsc: {
    // ── Pricing ──
    pricetype:   { label: 'Product Price Type', desc: 'Product pricing method type' },
    priceonty:   { label: 'Price On Type', desc: 'The Price On Type indicates the standard method used to calculate pricing' },
    listprice:   { label: 'List Price', desc: 'List price or retail price' },
    baseprice:   { label: 'Base Price', desc: 'Base price for this catalog entry' },
    prodcost:    { label: 'Replacement Cost', desc: 'Replacement cost for this catalog entry' },
    stndcost:    { label: 'Standard Cost', desc: 'Standard cost for this catalog entry' },
    speccostty:  { label: 'Special Price/Cost', desc: 'Special price or cost type' },
    rebatety:    { label: 'Rebate Type', desc: 'Rebate type code' },
    rebatecost:  { label: 'Rebate Cost', desc: 'Rebate cost amount' },
    pbseqno:     { label: 'Price Book Sequence #', desc: 'Price book sequence number' },
    // ── Product Info ──
    vendprod:    { label: 'Vendor Part #', desc: 'Vendor product number for this catalog entry' },
    vendno:      { label: 'Vendor #', desc: 'Vendor number' },
    prodline:    { label: 'Vendor Product Line', desc: 'Product line' },
    prodcat:     { label: 'Product Category', desc: 'Product category code' },
    slgroup:     { label: 'Supplier Group', desc: 'Supplier group code' },
    descrip_1:   { label: 'Description', desc: 'Primary description' },
    descrip_2:   { label: 'Description 2', desc: 'Secondary description' },
    descrip3:    { label: 'Extended Description', desc: 'Extended product description' },
    // ── UOM & Status ──
    unitstnd:    { label: 'Standard Pack UOM', desc: 'Standard pack unit of measure' },
    unitstock:   { label: 'Stocking UOM', desc: 'Stocking unit of measure' },
    statustype:  { label: 'Status', desc: 'Catalog entry status' },
    eccnclasscd: { label: 'ECCN', desc: 'Export Control Classification Number (ECCN)' },
    serlottype:  { label: 'Extended Type', desc: 'Serial/lot type for this catalog entry' },
    ncnr:        { label: 'Non Cancellable/Non Returnable', desc: 'Non cancellable/non returnable flag' },
    // ── User Defined ──
    user1:       { label: 'User Defined 1', desc: 'User defined field' },
    user2:       { label: 'User Defined 2', desc: 'User defined field' },
    user3:       { label: 'User Defined 3', desc: 'User defined field' },
    user4:       { label: 'User Defined 4', desc: 'User defined field' },
    user5:       { label: 'User Defined 5', desc: 'User defined field' },
    user6:       { label: 'User Defined 6', desc: 'User defined field' },
    user7:       { label: 'User Defined 7', desc: 'User defined field' },
    user8:       { label: 'User Defined 8', desc: 'User defined field' },
    user9:       { label: 'User Defined 9', desc: 'User defined field' },
    user10:      { label: 'User Defined 10', desc: 'User defined field' },
    user11:      { label: 'User Defined 11', desc: 'User defined field' },
    user12:      { label: 'User Defined 12', desc: 'User defined field' },
    user13:      { label: 'User Defined 13', desc: 'User defined field' },
    user14:      { label: 'User Defined 14', desc: 'User defined field' },
    user15:      { label: 'User Defined 15', desc: 'User defined field' },
    user16:      { label: 'User Defined 16', desc: 'User defined field' },
    user17:      { label: 'User Defined 17', desc: 'User defined field' },
    user18:      { label: 'User Defined 18', desc: 'User defined field' },
    user19:      { label: 'User Defined 19', desc: 'User defined field' },
    user20:      { label: 'User Defined 20', desc: 'User defined field' },
    user21:      { label: 'User Defined 21', desc: 'User defined field' },
    user22:      { label: 'User Defined 22', desc: 'User defined field' },
    user23:      { label: 'User Defined 23', desc: 'User defined field' },
    user24:      { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Transfer Header (WTEH) ───

  wteh: {
    duedt:       { label: 'Due Date', desc: 'Due' },
    orderaltno:  { label: 'Related Order #', desc: 'The related order number - contains the orderno, wtno, vano, or whse transfer number' },
    shipviaty:   { label: 'Ship Via', desc: 'This field describes the ship via. It is table driving in SASTT. ltdescri' },
    totqtyord:   { label: 'Total Qty Order', desc: 'Total Quantity Ordered' },
    totqtyshp:   { label: 'Total Qty Shipped', desc: 'Total Quantity Shipped' },
    totqtyrcv:   { label: 'Total Qty Received', desc: 'Total Quantity Received' },
    stagecd:     { label: 'Stage Code', desc: 'Transfer stage. 0 - Entered, 1 - Ordered, 2 - Shipped, 3 - Exception, 5 - Received, 9 - Closed' },
    shipfmwhse:  { label: 'Ship From Whse', desc: 'Ship from warehouse' },
    shiptowhse:  { label: 'Ship To Whse', desc: 'Ship to warehouse' },
    shipviaty:   { label: 'Ship Via', desc: 'Ship via type' },
  },

  // ─── Transfer Line (WTEL) ───

  wtel: {
    bofl:        { label: 'Backorder Flag', desc: 'Back Order Default flag' },
    approveinit: { label: 'Approval', desc: 'Operator id of the user that approved transfer' },
    qtyord:      { label: 'Qty Ordered', desc: 'Ordered' },
    qtyrcv:      { label: 'Qty Received', desc: 'Rcv Qty' },
    qtyship:     { label: 'Qty Shipped', desc: 'Quantity shipped' },
    shiptowhse:  { label: 'Ship To Whse', desc: 'Ship To Warehouse' },
    shipfmwhse:  { label: 'Ship From Whse', desc: 'Ship from warehouse' },
    prodcost:    { label: 'Product Cost', desc: 'The product cost of the line item. If the product is specially costed, this reflects that cost' },
    shipprod:    { label: 'Product', desc: 'Product shipped' },
    statustype:  { label: 'Status', desc: 'Line status' },
    unit:        { label: 'Unit', desc: 'Unit of measure' },
  },

  // ─── Customer Pricing (PDSC) ───

  pdsc: {
    actqty:        { label: 'Actual Qty', desc: 'Actual quantity' },
    modifierrebfl: { label: 'Allow With Line Rebate', desc: 'Allow with line rebate flag' },
    commtype:      { label: 'Comm Type', desc: 'Commission type' },
    ContractNo:    { label: 'Contract Number', desc: 'Contract number' },
    costmult:      { label: 'Cost Multiplier', desc: 'Cost multiplier' },
    costtype:      { label: 'Cost Type', desc: 'Cost type' },
    enddt:         { label: 'End Date', desc: 'Pricing end date' },
    hardmaxqtyfl:  { label: 'Hard Max Qty', desc: 'Hard maximum quantity flag' },
    hardpricefl:   { label: 'Hard Price', desc: 'Hard price flag' },
    qtyyymm:       { label: 'Last CCYYMM for Qty', desc: 'Last CCYYMM for quantity' },
    lastuseddt:    { label: 'Last Used Date', desc: 'Last used date' },
    lastuseddttz:  { label: 'Last Used Time', desc: 'Last used time' },
    prcdisc_1:     { label: 'Level 1 Amount discount', desc: 'Level 1 amount discount' },
    prcdisc_2:     { label: 'Level 2 Amount discount', desc: 'Level 2 amount discount' },
    prcdisc_3:     { label: 'Level 3 Amount discount', desc: 'Level 3 amount discount' },
    prcdisc_4:     { label: 'Level 4 Amount discount', desc: 'Level 4 amount discount' },
    prcdisc_5:     { label: 'Level 5 Amount discount', desc: 'Level 5 amount discount' },
    prcdisc_6:     { label: 'Level 6 Amount discount', desc: 'Level 6 amount discount' },
    prcdisc_7:     { label: 'Level 7 Amount discount', desc: 'Level 7 amount discount' },
    prcdisc_8:     { label: 'Level 8 Amount discount', desc: 'Level 8 amount discount' },
    prcdisc_9:     { label: 'Level 9 Amount discount', desc: 'Level 9 amount discount' },
    jobno:         { label: 'Line Refer', desc: 'Job/line reference number' },
    maxqtytype:    { label: 'Max Based On', desc: 'Maximum quantity based on type' },
    maxqty:        { label: 'Maximum Qty', desc: 'Maximum quantity' },
    minqty:        { label: 'Minimum Qty', desc: 'Minimum quantity' },
    modifiernm:    { label: 'Modifier Identifier', desc: 'Modifier identifier name' },
    priceonty:     { label: 'Multiplier', desc: 'Price on type / multiplier' },
    disctype:      { label: 'Order Discount Based On', desc: 'Order discount based on type' },
    ovrridepctdown: { label: 'Override Percent Down', desc: 'Override percent down' },
    ovrridepctup:  { label: 'Override Percent Up', desc: 'Override percent up' },
    prcmult_1:     { label: 'Price Detail Multiplier L1', desc: 'Price detail multiplier level 1' },
    prcmult_2:     { label: 'Price Detail Multiplier L2', desc: 'Price detail multiplier level 2' },
    prcmult_3:     { label: 'Price Detail Multiplier L3', desc: 'Price detail multiplier level 3' },
    prcmult_4:     { label: 'Price Detail Multiplier L4', desc: 'Price detail multiplier level 4' },
    prcmult_5:     { label: 'Price Detail Multiplier L5', desc: 'Price detail multiplier level 5' },
    prcmult_6:     { label: 'Price Detail Multiplier L6', desc: 'Price detail multiplier level 6' },
    prcmult_7:     { label: 'Price Detail Multiplier L7', desc: 'Price detail multiplier level 7' },
    prcmult_8:     { label: 'Price Detail Multiplier L8', desc: 'Price detail multiplier level 8' },
    prcmult_9:     { label: 'Price Detail Multiplier L9', desc: 'Price detail multiplier level 9' },
    prctype:       { label: 'Price Level', desc: 'Price level type' },
    pricety:       { label: 'Price Method', desc: 'Price method type' },
    PriceSheet:    { label: 'Price Sheet', desc: 'Price sheet identifier' },
    pround:        { label: 'Pricing - Round', desc: 'Pricing rounding method' },
    costbasedon:   { label: 'Pricing Cost Based On', desc: 'Pricing cost based on' },
    pricecostty:   { label: 'Pricing Cost Type', desc: 'Pricing cost type' },
    prodcost:      { label: 'Product Cost', desc: 'Product cost' },
    promofl:       { label: 'Promotional', desc: 'Promotional flag' },
    qtybrk_1:      { label: 'Quantity Break 1', desc: 'Quantity break level 1' },
    qtybrk_2:      { label: 'Quantity Break 2', desc: 'Quantity break level 2' },
    qtybrk_3:      { label: 'Quantity Break 3', desc: 'Quantity break level 3' },
    qtybrk_4:      { label: 'Quantity Break 4', desc: 'Quantity break level 4' },
    qtybrk_5:      { label: 'Quantity Break 5', desc: 'Quantity break level 5' },
    qtybrk_6:      { label: 'Quantity Break 6', desc: 'Quantity break level 6' },
    qtybrk_7:      { label: 'Quantity Break 7', desc: 'Quantity break level 7' },
    qtybrk_8:      { label: 'Quantity Break 8', desc: 'Quantity break level 8' },
    qtybreakty:    { label: 'Quantity Break On', desc: 'Quantity break on type' },
    qtytype:       { label: 'Quantity Break Per', desc: 'Quantity break per type' },
    quotefl:       { label: 'Quote', desc: 'Quote flag' },
    quoteno:       { label: 'Quote Number', desc: 'Quote number' },
    refer:         { label: 'Reference', desc: 'Reference' },
    slchgdt:       { label: 'SL Update Date', desc: 'SL update date' },
    slchgdttz:     { label: 'SL Update Time', desc: 'SL update time' },
    stacktrace:    { label: 'Stack Trace', desc: 'Stack trace' },
    statustype:    { label: 'Status', desc: 'Pricing record status' },
    ptarget:       { label: 'Target', desc: 'Price target' },
    termsdiscfl:   { label: 'Terms Discount', desc: 'Terms discount flag' },
    termspct:      { label: 'Terms Discount %', desc: 'Terms discount percentage' },
    user1:         { label: 'User 1', desc: 'User defined field 1' },
    user2:         { label: 'User 2', desc: 'User defined field 2' },
    user3:         { label: 'User 3', desc: 'User defined field 3' },
    user4:         { label: 'User 4', desc: 'User defined field 4' },
    user5:         { label: 'User 5', desc: 'User defined field 5' },
    user6:         { label: 'User 6', desc: 'User defined field 6' },
    user7:         { label: 'User 7', desc: 'User defined field 7' },
    user8:         { label: 'User 8', desc: 'User defined field 8' },
    user9:         { label: 'User 9', desc: 'User defined field 9' },
    pexactrnd:     { label: 'User Tgt', desc: 'User target / exact round' },
  },

  // ─── Vendor Pricing (PDSV) ───

  pdsv: {
    buytype:       { label: 'Buy Type', desc: 'Buy type' },
    enddt:         { label: 'End Date', desc: 'Pricing end date' },
    prcdisc_1:     { label: 'Level 1 Amount discount', desc: 'Level 1 amount discount' },
    prcdisc_2:     { label: 'Level 2 Amount discount', desc: 'Level 2 amount discount' },
    prcdisc_3:     { label: 'Level 3 Amount discount', desc: 'Level 3 amount discount' },
    prcdisc_4:     { label: 'Level 4 Amount discount', desc: 'Level 4 amount discount' },
    prcdisc_5:     { label: 'Level 5 Amount discount', desc: 'Level 5 amount discount' },
    prcdisc_6:     { label: 'Level 6 Amount discount', desc: 'Level 6 amount discount' },
    prcdisc_7:     { label: 'Level 7 Amount discount', desc: 'Level 7 amount discount' },
    prcdisc_8:     { label: 'Level 8 Amount discount', desc: 'Level 8 amount discount' },
    prcdisc_9:     { label: 'Level 9 Amount discount', desc: 'Level 9 amount discount' },
    prcmult_1:     { label: 'Price Detail Multiplier L1', desc: 'Price detail multiplier level 1' },
    prcmult_2:     { label: 'Price Detail Multiplier L2', desc: 'Price detail multiplier level 2' },
    prcmult_3:     { label: 'Price Detail Multiplier L3', desc: 'Price detail multiplier level 3' },
    prcmult_4:     { label: 'Price Detail Multiplier L4', desc: 'Price detail multiplier level 4' },
    prcmult_5:     { label: 'Price Detail Multiplier L5', desc: 'Price detail multiplier level 5' },
    prcmult_6:     { label: 'Price Detail Multiplier L6', desc: 'Price detail multiplier level 6' },
    prcmult_7:     { label: 'Price Detail Multiplier L7', desc: 'Price detail multiplier level 7' },
    prcmult_8:     { label: 'Price Detail Multiplier L8', desc: 'Price detail multiplier level 8' },
    prcmult_9:     { label: 'Price Detail Multiplier L9', desc: 'Price detail multiplier level 9' },
    qtybrk_1:      { label: 'Quantity Break 1', desc: 'Quantity break level 1' },
    qtybrk_2:      { label: 'Quantity Break 2', desc: 'Quantity break level 2' },
    qtybrk_3:      { label: 'Quantity Break 3', desc: 'Quantity break level 3' },
    qtybrk_4:      { label: 'Quantity Break 4', desc: 'Quantity break level 4' },
    qtybrk_5:      { label: 'Quantity Break 5', desc: 'Quantity break level 5' },
    qtybrk_6:      { label: 'Quantity Break 6', desc: 'Quantity break level 6' },
    qtybrk_7:      { label: 'Quantity Break 7', desc: 'Quantity break level 7' },
    qtybrk_8:      { label: 'Quantity Break 8', desc: 'Quantity break level 8' },
    refer:         { label: 'Reference', desc: 'Reference' },
    slchgdt:       { label: 'SL Update Date', desc: 'SL update date' },
    slchgdttz:     { label: 'SL Update Time', desc: 'SL update time' },
    stacktrace:    { label: 'Stack Trace', desc: 'Stack trace' },
    startdt:       { label: 'Start Date', desc: 'Pricing start date' },
    statustype:    { label: 'Status', desc: 'Pricing record status' },
    vendorprice:   { label: 'Vendor Price', desc: 'Vendor price' },
    user1:         { label: 'User 1', desc: 'User defined field 1' },
    user2:         { label: 'User 2', desc: 'User defined field 2' },
    user3:         { label: 'User 3', desc: 'User defined field 3' },
    user4:         { label: 'User 4', desc: 'User defined field 4' },
    user5:         { label: 'User 5', desc: 'User defined field 5' },
    user6:         { label: 'User 6', desc: 'User defined field 6' },
    user7:         { label: 'User 7', desc: 'User defined field 7' },
    user8:         { label: 'User 8', desc: 'User defined field 8' },
    user9:         { label: 'User 9', desc: 'User defined field 9' },
  },

  // ─── Vendor Master (APSV) ───

  apsv: {
    // ── Status & Terms ──
    statustype:       { label: 'Status', desc: 'Vendor active/inactive status' },
    termstype:        { label: 'Terms Type', desc: 'Vendor payment terms' },
    paymentty:        { label: 'Payment Terms', desc: 'Payment terms description' },
    shipviaty:        { label: 'Ship Via', desc: 'Ship via type' },
    frttermscd:       { label: 'Freight Terms', desc: 'Freight terms code' },
    freightexpectedty: { label: 'Freight Expected', desc: 'Freight expected type' },
    fobfl:            { label: 'FOB Destination', desc: 'Free on board destination flag' },
    currencyty:       { label: 'Currency Code', desc: 'Currency type' },
    // ── Identity ──
    name:             { label: 'Vendor Name', desc: 'Vendor name' },
    lookupnm:         { label: 'Lookup Name', desc: 'Vendor lookup name' },
    vendtype:         { label: 'Vendor Type', desc: 'Vendor type description' },
    apvendcls:        { label: 'Class', desc: 'Vendor classification' },
    proctype:         { label: 'Proc Type', desc: 'Processing type' },
    divno:            { label: 'Division', desc: 'Division number' },
    langcd:           { label: 'Language', desc: 'Language code' },
    // ── Address ──
    addr_1:           { label: 'Address', desc: 'Vendor address line 1' },
    addr_2:           { label: 'Address 2', desc: 'Vendor address line 2' },
    addr3:            { label: 'Address 3', desc: 'Third address line' },
    city:             { label: 'City', desc: 'City' },
    state:            { label: 'State', desc: 'State code' },
    zipcd:            { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:        { label: 'Country', desc: 'Country abbreviation' },
    // ── Contact ──
    email:            { label: 'Email Address', desc: 'Vendor email' },
    phoneno:          { label: 'Phone', desc: 'Vendor phone number' },
    faxphoneno:       { label: 'Fax Phone', desc: 'Vendor fax number' },
    edi820email:      { label: 'Electronic Remittance Email', desc: 'Electronic remittance email for supplier' },
    // ── Tax & 1099 ──
    fedtaxid:         { label: 'Tax ID #', desc: 'Federal tax ID number' },
    fed1099no:        { label: '1099 Number', desc: '1099 number' },
    fed1099box:       { label: '1099 Type', desc: '1099 type' },
    ap1099nm:         { label: '1099 Type Description', desc: '1099 type description' },
    resalefl:         { label: 'Resale Flag', desc: 'Resale flag' },
    // ── Banking ──
    bankno:           { label: 'Bank #', desc: 'Bank number' },
    vendbankacct:     { label: 'Bank Account #', desc: 'Vendor bank account number' },
    vendbankacctname: { label: 'Bank Account Name', desc: 'Vendor bank account name' },
    vendbanktrno:     { label: 'Transit Routing #', desc: 'Bank transit routing number' },
    // ── Misc ──
    comment:          { label: 'Comment', desc: 'Vendor comment' },
    dunsno:           { label: 'DUNS #', desc: 'DUNS number' },
    disputevndfl:     { label: 'Dispute', desc: 'Dispute vendor flag' },
    erebtype:         { label: 'Rebates', desc: 'Rebate type' },
    // ── User Defined ──
    user1:            { label: 'User Defined 1', desc: 'User defined field' },
    user2:            { label: 'User Defined 2', desc: 'User defined field' },
    user3:            { label: 'User Defined 3', desc: 'User defined field' },
    user4:            { label: 'User Defined 4', desc: 'User defined field' },
    user5:            { label: 'User Defined 5', desc: 'User defined field' },
    user6:            { label: 'User Defined 6', desc: 'User defined field' },
    user7:            { label: 'User Defined 7', desc: 'User defined field' },
    user8:            { label: 'User Defined 8', desc: 'User defined field' },
    user9:            { label: 'User Defined 9', desc: 'User defined field' },
    user10:           { label: 'User Defined 10', desc: 'User defined field' },
    user11:           { label: 'User Defined 11', desc: 'User defined field' },
    user12:           { label: 'User Defined 12', desc: 'User defined field' },
    user13:           { label: 'User Defined 13', desc: 'User defined field' },
    user14:           { label: 'User Defined 14', desc: 'User defined field' },
    user15:           { label: 'User Defined 15', desc: 'User defined field' },
    user16:           { label: 'User Defined 16', desc: 'User defined field' },
    user17:           { label: 'User Defined 17', desc: 'User defined field' },
    user18:           { label: 'User Defined 18', desc: 'User defined field' },
    user19:           { label: 'User Defined 19', desc: 'User defined field' },
    user20:           { label: 'User Defined 20', desc: 'User defined field' },
    user21:           { label: 'User Defined 21', desc: 'User defined field' },
    user22:           { label: 'User Defined 22', desc: 'User defined field' },
    user23:           { label: 'User Defined 23', desc: 'User defined field' },
    user24:           { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Vendor Ship-From (APSS) ───

  apss: {
    // ── Status & Terms ──
    statustype:       { label: 'Status', desc: 'Ship-from active/inactive status' },
    termstype:        { label: 'Terms Type', desc: 'Ship-from payment terms' },
    shipviaty:        { label: 'Ship Via', desc: 'Ship via type for this ship-from location' },
    frttermscd:       { label: 'Freight Terms', desc: 'Freight terms code' },
    freightexpectedty: { label: 'Freight Expected', desc: 'Freight expected type' },
    // ── Flags ──
    allowpofl:        { label: 'Allow PO', desc: 'Allow purchase orders flag' },
    bofl:             { label: 'B/O Ok', desc: 'Backorder allowed flag' },
    limitshipvia:     { label: 'Limit Ship Via', desc: 'Limit ship via flag' },
    synccrmfl:        { label: 'Sync To CRM', desc: 'Sync to CRM flag' },
    epotype:          { label: 'Purchase Order Type', desc: 'Purchase order type' },
    transferloc:      { label: 'Transfer Location', desc: 'Transfer location' },
    langcd:           { label: 'Language Code', desc: 'Language code' },
    // ── Name & Address ──
    name:             { label: 'Vendor Name', desc: 'Ship-from name' },
    addr_1:           { label: 'Address', desc: 'Ship-from address line 1' },
    addr_2:           { label: 'Address 2', desc: 'Ship-from address line 2' },
    addr3:            { label: 'Address 3', desc: 'Third address line' },
    city:             { label: 'City', desc: 'City' },
    state:            { label: 'State', desc: 'State code' },
    zipcd:            { label: 'Zip Code', desc: 'Postal/zip code' },
    countrycd:        { label: 'Country', desc: 'Country abbreviation' },
    // ── Contact ──
    email:            { label: 'Email Address', desc: 'Ship-from email' },
    phoneno:          { label: 'Phone', desc: 'Ship-from phone number' },
    faxphoneno:       { label: 'Fax Phone', desc: 'Ship-from fax number' },
    // ── User Defined ──
    user1:            { label: 'User Defined 1', desc: 'User defined field' },
    user2:            { label: 'User Defined 2', desc: 'User defined field' },
    user3:            { label: 'User Defined 3', desc: 'User defined field' },
    user4:            { label: 'User Defined 4', desc: 'User defined field' },
    user5:            { label: 'User Defined 5', desc: 'User defined field' },
    user6:            { label: 'User Defined 6', desc: 'User defined field' },
    user7:            { label: 'User Defined 7', desc: 'User defined field' },
    user8:            { label: 'User Defined 8', desc: 'User defined field' },
    user9:            { label: 'User Defined 9', desc: 'User defined field' },
    user10:           { label: 'User Defined 10', desc: 'User defined field' },
    user11:           { label: 'User Defined 11', desc: 'User defined field' },
    user12:           { label: 'User Defined 12', desc: 'User defined field' },
    user13:           { label: 'User Defined 13', desc: 'User defined field' },
    user14:           { label: 'User Defined 14', desc: 'User defined field' },
    user15:           { label: 'User Defined 15', desc: 'User defined field' },
    user16:           { label: 'User Defined 16', desc: 'User defined field' },
    user17:           { label: 'User Defined 17', desc: 'User defined field' },
    user18:           { label: 'User Defined 18', desc: 'User defined field' },
    user19:           { label: 'User Defined 19', desc: 'User defined field' },
    user20:           { label: 'User Defined 20', desc: 'User defined field' },
    user21:           { label: 'User Defined 21', desc: 'User defined field' },
    user22:           { label: 'User Defined 22', desc: 'User defined field' },
    user23:           { label: 'User Defined 23', desc: 'User defined field' },
    user24:           { label: 'User Defined 24', desc: 'User defined field' },
  },

  // ─── Security: SASOO (Operator Setup) ───

  sasoo: {
    arecedbfl:        { label: 'A/R Debits', desc: 'A/R debits flag' },
    notesfl:          { label: 'Access Notes', desc: 'Access notes flag' },
    promoprcwin:      { label: 'Access OE Promo Price Window', desc: 'Access OE promo price window' },
    secnotefl:        { label: 'Access Secured Notes', desc: 'Access secured notes flag' },
    catconvertfl:     { label: 'Allow Catalog Stocking', desc: 'Allow catalog stocking' },
    oenoinvoicefl:    { label: 'Allow For Our Records Only Invoice', desc: 'Allow for our records only invoice' },
    updglapty:        { label: 'Allow GL update AP records', desc: 'Allow GL update AP records' },
    updglarty:        { label: 'Allow GL update AR records', desc: 'Allow GL update AR records' },
    updglicty:        { label: 'Allow GL update IC records', desc: 'Allow GL update IC records' },
    intercofl:        { label: 'Allow InterCo Processing', desc: 'Allow intercompany processing' },
    oeorigpromisefl:  { label: 'Allow Maintenance of Orig Promised Date', desc: 'Allow maintenance of original promised date' },
    ncnrfl:           { label: 'Allow NCNR Entry', desc: 'Allow NCNR entry' },
    nscommfl:         { label: 'Allow Non-Stock Comm Type Entry', desc: 'Allow non-stock commission type entry' },
    nonstockfl:       { label: 'Allow Non-Stock Entry', desc: 'Allow non-stock entry' },
    nsquoteoanty:     { label: 'Allow OAN-NS Create in Quote', desc: 'Allow OAN-NS create in quote' },
    oeslsrepfl:       { label: 'Allow OE Salesrep Override', desc: 'Allow OE salesrep override' },
    resalefl:         { label: 'Allow PO Non-Resale Entry', desc: 'Allow PO non-resale entry' },
    oetietype:        { label: 'Allow PO,WT,PO&WT,No Ties', desc: 'Allow PO/WT tie type' },
    pocrctfl:         { label: 'Allow Purchase Order Corrections', desc: 'Allow PO corrections' },
    shiptofl:         { label: 'Allow Ship To Address Override', desc: 'Allow ship-to address override' },
    termsoverfl:      { label: 'Allow Terms Override', desc: 'Allow terms override' },
    icacquiredtfl:    { label: 'Allow user to maintain ICSW Acquire Date', desc: 'Allow user to maintain ICSW acquire date' },
    altoperinit:      { label: 'Alternate Operator', desc: 'Alternate operator' },
    apsuperfl:        { label: 'Ap Supervisor', desc: 'AP supervisor flag' },
    wtapprwhse:       { label: 'Approve WTs for Whse', desc: 'Approve warehouse transfers for warehouse' },
    holdforauthdefault: { label: 'Auth Hold Default', desc: 'Authorization hold default' },
    arwrtofflim:      { label: 'Cash Receipts Writeoff Limit', desc: 'Cash receipts writeoff limit' },
    iccatcrtty:       { label: 'Catalog Create Type', desc: 'Catalog create type' },
    chgbalfl:         { label: 'Change Balances', desc: 'Change balances flag' },
    chgglcostfl:      { label: 'Change GL Cost', desc: 'Change GL cost flag' },
    autobillwhsefl:   { label: 'Create OE Billing Orders From WT', desc: 'Create OE billing orders from WT' },
    credpostfl:       { label: 'Customer Credits', desc: 'Customer credits posting flag' },
    printernm:        { label: 'Default Printer Name', desc: 'Default printer name' },
    whse:             { label: 'Default Warehouse', desc: 'Default warehouse' },
    oedotyamtmax:     { label: 'DO Max Hold Dollar Value', desc: 'DO max hold dollar value' },
    podotyamtmax:     { label: 'DO Max Hold Dollar Value', desc: 'PO DO max hold dollar value' },
    oedotymrgpctmax:  { label: 'DO Max Hold Margin %', desc: 'DO max hold margin percent' },
    oedotymrgamtmax:  { label: 'DO Max Hold Margin Amt', desc: 'DO max hold margin amount' },
    oedotyamtmin:     { label: 'DO Min Hold Dollar Value', desc: 'DO min hold dollar value' },
    podotyamtmin:     { label: 'DO Min Hold Dollar Value', desc: 'PO DO min hold dollar value' },
    oedotymrgpctmin:  { label: 'DO Min Hold Margin %', desc: 'DO min hold margin percent' },
    oedotymrgamtmin:  { label: 'DO Min Hold Margin Amt', desc: 'DO min hold margin amount' },
    reqtakenfl:       { label: 'Force Taken By Window', desc: 'Force taken by window' },
    gloverfl:         { label: 'GLET Override Flag', desc: 'GLET override flag' },
    oehardprcovrfl:   { label: 'Hard Price Override', desc: 'Hard price override' },
    icmanlistty:      { label: 'ICAMU Manual List Type', desc: 'ICAMU manual list type' },
    icmassmaintfl:    { label: 'ICAMU Mass Maintenance', desc: 'ICAMU mass maintenance' },
    icmanlistoverfl:  { label: 'ICAMU Override Manual List Operator', desc: 'ICAMU override manual list operator' },
    jmapprvty:        { label: 'JM Prc/Cst Approve Type', desc: 'JM price/cost approve type' },
    jmupdprtpofl:     { label: 'JMEC Allow Printed PO Update', desc: 'JMEC allow printed PO update' },
    kptietype:        { label: 'KP PO/WT Ties', desc: 'KP PO/WT ties type' },
    kpverchg:         { label: 'KP Prev Version Change', desc: 'KP previous version change' },
    kpveruse:         { label: 'KP Prev Version Usage', desc: 'KP previous version usage' },
    limitholdcds:     { label: 'Limit Hold Codes', desc: 'Limit hold codes' },
    limitslsrepfl:    { label: 'Limit Sales Rep', desc: 'Limit sales rep flag' },
    limittakenbyfl:   { label: 'Limit Taken By', desc: 'Limit taken by flag' },
    oesotyamtmax:     { label: 'Max Hold Dollar Value', desc: 'Max hold dollar value' },
    popotyamtmax:     { label: 'Max Hold Dollar Value', desc: 'PO max hold dollar value' },
    oesotymrgpctmax:  { label: 'Max Hold Margin %', desc: 'Max hold margin percent' },
    oesotymrgamtmax:  { label: 'Max Hold Margin Amt', desc: 'Max hold margin amount' },
    popotyamtmin:     { label: 'Min Hold Dollar Value', desc: 'PO min hold dollar value' },
    oesotyamtmin:     { label: 'Min Hold Dollar Value', desc: 'Min hold dollar value' },
    oesotymrgpctmin:  { label: 'Min Hold Margin %', desc: 'Min hold margin percent' },
    oesotymrgamtmin:  { label: 'Min Hold Margin Amt', desc: 'Min hold margin amount' },
    nscrtoanty:       { label: 'OAN-NS Stocking', desc: 'OAN-NS stocking type' },
    oechglntypefl:    { label: 'OE Change Line Type', desc: 'OE change line type' },
    oecostoverty:     { label: 'OE Cost Override Type', desc: 'OE cost override type' },
    oensqtyshpty:     { label: 'OE NS Ship Qty Override Type', desc: 'OE non-stock ship quantity override type' },
    oeqtyshipty:      { label: 'OE Ship Qty Override Type', desc: 'OE ship quantity override type' },
    originchangefl:   { label: 'Order Origin Change', desc: 'Order origin change flag' },
    holdintlfl:       { label: 'Override International Hold', desc: 'Override international hold' },
    holdoverfl:       { label: 'Override Order Hold', desc: 'Override order hold' },
    oepricefl:        { label: 'Price/Discount Options', desc: 'Price/discount options' },
    saspgroup:        { label: 'Printer Group', desc: 'Printer group' },
    rprinternm:       { label: 'Receipt Printer', desc: 'Receipt printer' },
    icswstchgfl:      { label: 'Status Copy/Chg For OAN-NS', desc: 'Status copy/change for OAN-NS' },
    superfl:          { label: 'Supervisor Status', desc: 'Supervisor status' },
    sysadminfl:       { label: 'System Administrator', desc: 'System administrator flag' },
    oetoleranceovrfl: { label: 'Tolerance Override', desc: 'Tolerance override' },
    custnotesfl:      { label: 'Update Customer Notes', desc: 'Update customer notes flag' },
    oeupdtcustpofl:   { label: 'Update Customer PO#', desc: 'Update customer PO number' },
    prodnotesfl:      { label: 'Update Product Notes', desc: 'Update product notes flag' },
    vendnotesfl:      { label: 'Update Vendor Notes', desc: 'Update vendor notes flag' },
    useprevnsfl:      { label: 'Use Previous Non-Stock Settings', desc: 'Use previous non-stock settings' },
    usergroup:        { label: 'User Group', desc: 'User group' },
    logindt:          { label: 'User Last Login Date', desc: 'User last login date' },
    valtakenfl:       { label: 'Validate Taken By', desc: 'Validate taken by flag' },
    vendpostfl:       { label: 'Vendor Returns/Credits', desc: 'Vendor returns/credits posting flag' },
    seecostfl:        { label: 'View Costs', desc: 'View costs flag' },
    xconocostfl:      { label: 'View Cross Cono Costs', desc: 'View cross cono costs flag' },
  },

  // ─── Security: PV_USER (User Profile) ───

  pv_user: {
    ActivitySecrLev:          { label: 'Activity Security', desc: 'Activity security level' },
    AOSecurity:               { label: 'Admin Options Security', desc: 'Admin options security' },
    allowbalancegiftfl:       { label: 'Allow Access to Gift Card Balance', desc: 'Allow access to gift card balance' },
    ActivityOtherOperFl:      { label: 'Allow Access to Other Operator Activities', desc: 'Allow access to other operator activities' },
    allowactivategiftfl:      { label: 'Allow Activation of Gift Card', desc: 'Allow activation of gift card' },
    updategltrans:            { label: 'Allow GL Entry Transactions Final Update', desc: 'Allow GL entry transactions final update' },
    nsfoverfl:                { label: 'Allow NSF Fee Override in ARECR', desc: 'Allow NSF fee override in ARECR' },
    seccredmgrfl:             { label: 'Allow Override of Login Credit Mgr', desc: 'Allow override of login credit manager' },
    oereassignarfl:           { label: 'Allow Reassign Customer/Ship To', desc: 'Allow reassign customer/ship to' },
    UnlimitedWebAccess:       { label: 'Allow Unlimited Web Access', desc: 'Allow unlimited web access' },
    oeunlinkdotiesfl:         { label: 'Allow Unlink of DO Ties', desc: 'Allow unlink of DO ties' },
    profileuserset:           { label: 'Allow User Specific Settings', desc: 'Allow user specific settings' },
    EntryLayout:              { label: 'Allow User to Change Entry Layout', desc: 'Allow user to change entry layout' },
    ChangeProfiles:           { label: 'Allow User to Change Their Profile', desc: 'Allow user to change their profile' },
    apeiusecostfl:            { label: 'Allow User to Chg AP Recon Cost Type', desc: 'Allow user to change AP recon cost type' },
    apeiovertolfl:            { label: 'Allow User to Override Update Tolerances', desc: 'Allow user to override update tolerances' },
    apeiaddonfl:              { label: 'Allow User to Process Addon Invoices', desc: 'Allow user to process addon invoices' },
    apeiexpensefl:            { label: 'Allow User to Process Expense Invoices', desc: 'Allow user to process expense invoices' },
    apeitradefl:              { label: 'Allow User to Process Trade Invoices', desc: 'Allow user to process trade invoices' },
    restricteditapfl:         { label: 'Allowed Editing of Restricted Editing AP Records', desc: 'Allowed editing of restricted AP records' },
    restricteditarfl:         { label: 'Allowed Editing of Restricted Editing AR Records', desc: 'Allowed editing of restricted AR records' },
    ContactMgmntSecrLev:      { label: 'Contact Management Security', desc: 'Contact management security level' },
    Disabled:                 { label: 'Disabled', desc: 'Disabled flag' },
    webextensiontype:         { label: 'Extension Access Level', desc: 'Extension access level' },
    oeprodtypecostoverty:     { label: 'Product Type Cost Override', desc: 'Product type cost override' },
    reqdraweridfl:            { label: 'Require Drawer ID', desc: 'Require drawer ID flag' },
    divnorestrictapfl:        { label: 'Restrict Data Access For AP', desc: 'Restrict data access for AP' },
    divnorestrictarfl:        { label: 'Restrict Data Access For AR', desc: 'Restrict data access for AR' },
    divnorestrictcrfl:        { label: 'Restrict Data Access For CR', desc: 'Restrict data access for CR' },
    divnorestrictglfl:        { label: 'Restrict Data Access For GL', desc: 'Restrict data access for GL' },
    divnorestricticfl:        { label: 'Restrict Data Access For IC', desc: 'Restrict data access for IC' },
    divnorestrictoefl:        { label: 'Restrict Data Access For OE', desc: 'Restrict data access for OE' },
    divnorestrictpofl:        { label: 'Restrict Data Access For PO', desc: 'Restrict data access for PO' },
    divnorestrictwtfl:        { label: 'Restrict Data Access For WT', desc: 'Restrict data access for WT' },
    divnorestrictwtallfl:     { label: 'Restrict Data Access For WT-Allow Across Divisions', desc: 'Restrict data access for WT allow across divisions' },
    pdrestrictty:             { label: 'Restrict Pricing And Price Sheets', desc: 'Restrict pricing and price sheets' },
    twlrestrictwhsefl:        { label: 'Restrict to TWL Warehouse Only', desc: 'Restrict to TWL warehouse only' },
    rolename:                 { label: 'Role Name', desc: 'Role name' },
    webmodificationaccesslevel: { label: 'Save/Load Web Modifications', desc: 'Save/load web modifications access level' },
    websettingaccesslevel:    { label: 'Save/Load Web Settings', desc: 'Save/load web settings access level' },
    UserName:                 { label: 'User Name', desc: 'User name' },
    ProfileName:              { label: 'User Profile', desc: 'User profile name' },
    oevendcontaccesscd:       { label: 'Vendor Contract Pricing Access for Order Entry', desc: 'Vendor contract pricing access for OE' },
    povendcontaccesscd:       { label: 'Vendor Contract Pricing Access for Purchasing', desc: 'Vendor contract pricing access for purchasing' },
    viewcosttype:             { label: 'View Cost Type Override', desc: 'View cost type override' },
    webprofilename:           { label: 'WebUI User Profile', desc: 'WebUI user profile name' },
  },

  // ─── Security: PV_SECURE (Function Security) ───

  pv_secure: {
    FunctionSecurity:  { label: 'Function Security', desc: 'Function security level' },
    FolderDelimiter:   { label: 'Folder Delimiter', desc: 'Folder delimiter' },
    MenuSet:           { label: 'Menu Set', desc: 'Menu set' },
  },

  // ─── Security: AUTHSECURE (Authorization Security) ───

  authsecure: {
    action_datetime:  { label: 'Action Datetime', desc: 'Action datetime' },
    actionby:         { label: 'Action Taken By', desc: 'Action taken by' },
    authtransid:      { label: 'Authtrans Recid', desc: 'Authorization transaction record ID' },
    ourproc:          { label: 'Function', desc: 'Function/process' },
    key1:             { label: 'Key 1', desc: 'Key 1' },
    key2:             { label: 'Key 2', desc: 'Key 2' },
    mode:             { label: 'Mode', desc: 'Mode' },
    securcd:          { label: 'Securcd', desc: 'Security code' },
    authstatus:       { label: 'Status', desc: 'Authorization status' },
    transtype:        { label: 'Type', desc: 'Transaction type' },
  },
};

/**
 * Get tracked fields for a table. Returns empty object if table not registered.
 */
function getTrackedFields(table) {
  return TRACKED_FIELDS[table.toLowerCase()] || {};
}

/**
 * Get table config (key field names). Returns default pono/posuf if not registered.
 */
function getTableConfig(table) {
  return TABLE_CONFIG[table.toLowerCase()] || { recordKey: 'pono', suffixKey: 'posuf', lineKey: null };
}

module.exports = {
  TRACKED_FIELDS,
  TABLE_CONFIG,
  getTrackedFields,
  getTableConfig,
};
